export interface IComprovativos {
    id: Number,
    nomeEmpresa: String,
    type: String,
    interveniente: String,
    dtValidade: String,
    dtEntrada: String,
    status: String,
    socialDenomination: String,
    flagComprovativoSociedade: Boolean,
    flagComprovativoBEF: Boolean,
    flagComprovativoFiscal: Boolean,
    flagComprovativoRCBE: Boolean,
    documentosIntervenientes: Boolean,
    nomeInterveniente: String,
    flagComprovativoDocID: Boolean,
    flagComprovativoFiscalInter: Boolean,
    flagProcuracao: Boolean,
    filename: String,
    url: String
};
