import { HttpClient } from '@angular/common/http';
import { Component, Inject, Injectable, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute, NavigationExtras, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { DataService } from '../nav-menu-interna/data.service';
import { SubmissionService } from '../submission/service/submission-service.service';
import { CountryInformation } from '../table-info/ITable-info.interface';
import { TableInfoService } from '../table-info/table-info.service';
import * as $ from 'jquery';
import { SubmissionPostTemplate } from '../submission/ISubmission.interface';
import { Client } from '../client/Client.interface';
import { ClientService } from '../client/client.service';
@Component({
  selector: 'app-countrys',
  templateUrl: './countrys.component.html'
})
export class CountrysComponent implements OnInit {
  continente = '';

  lstCountry = [];
  lstCountry1 = [];
  lstCountry2 = [];
  contPais = [];

  continenteName: string;

  lstPaisPreenchido = [];

  inputEuropa: boolean = false;
  inputOceania: boolean = false;
  inputAsia: boolean = false;
  inputAfrica: boolean = false;
  inputAmericas: boolean = false;
  inputTypeEuropa: boolean;
  inputTypeOceania: boolean;
  inputTypeAmericas: boolean;
  inputTypeAsia: boolean;
  inputTypeAfrica: boolean;
  statusValue: boolean = false;

  clientExists: boolean;
  associatedWithGroupOrFranchise: boolean = false;
  isAssociatedWithFranchise: boolean;
  form: FormGroup;

  public map = new Map();
  public currentPage: number;
  public subscription: Subscription;

  countryList: CountryInformation[] = [];
  continentsList: string[] = [];
  checkedContinents = [];

  tipologia: any;
  NIFNIPC: any;
  client: Client;
  clientId: string;

  currentClient: any = {};
  documentsList = []; //lista de documentos do utilizador


  ngOnInit() {
    this.initializeForm();
    this.subscription = this.data.currentData.subscribe(map => this.map = map);
    this.subscription = this.data.currentPage.subscribe(currentPage => this.currentPage = currentPage);
    
  }

  constructor(private http: HttpClient, @Inject('BASE_URL') private baseUrl: string,
    private route: Router, private tableInfo: TableInfoService, private submissionService: SubmissionService, private data: DataService,
    private router: ActivatedRoute, private clientService: ClientService) {

    if (this.route.getCurrentNavigation().extras.state) {
      this.clientExists = this.route.getCurrentNavigation().extras.state["clientExists"];
      this.tipologia = this.route.getCurrentNavigation().extras.state["tipologia"];
      this.NIFNIPC = this.route.getCurrentNavigation().extras.state["NIFNIPC"];
      this.client = this.route.getCurrentNavigation().extras.state["client"];
      this.clientId = this.route.getCurrentNavigation().extras.state["clientId"];
      console.log("client exists ", this.clientExists);
      console.log(this.route.getCurrentNavigation().extras);
    }

    this.clientId = String(this.router.snapshot.params['id']);

    console.log(this.clientId);
    //Chamada à API para receber todos os Paises
    this.tableInfo.GetAllCountries().subscribe(result => {
      this.countryList = result;
      console.log("FETCH PAISES");
    }, error => console.log(error));

    console.log("por entrar no clientbyid");
    this.clientService.getClientByID("88dab4e9-3818-4491-addb-f518ae649e5a", "8ed4a062-b943-51ad-4ea9-392bb0a23bac", "22195900002451", "fQkRbjO+7kGqtbjwnDMAag==").subscribe(result => {
      console.log("entrou no getclientbyid");
      this.currentClient = result;
      console.log(result);
      console.log(this.currentClient);
    });
  }

  initializeForm() {
    this.form = new FormGroup({
      franchiseName: new FormControl(/*this.client.companyName*/'', ),
      expectableAnualInvoicing: new FormControl(/*this.client.knowYourSales.estimatedAnualRevenue, Validators.required*/),
      services: new FormControl('', /*Validators.required*/),
      transactionsAverage: new FormControl(/*this.client.knowYourSales.averageTransactions, Validators.required*/),
      associatedWithGroupOrFranchise: new FormControl(this.associatedWithGroupOrFranchise),
      NIPCGroup: new FormControl(/*this.client.businessGroup.fiscalId*/),
      preferenceDocuments: new FormControl(/*this.client.documentationDeliveryMethod, Validators.required*/),
      inputEuropa: new FormControl(this.inputEuropa),
      inputAfrica: new FormControl(this.inputAfrica),
      inputAmerica: new FormControl(this.inputAmericas),
      inputOceania: new FormControl(this.inputOceania),
      inputAsia: new FormControl(this.inputTypeAsia)
    })

    this.form.get("franchiseName").valueChanges.subscribe(v => {
      if (v !== '') {
        this.isAssociatedWithFranchise = true;
      } else {
        this.isAssociatedWithFranchise = undefined;
      }
    })

    this.form.get("NIPCGroup").valueChanges.subscribe(v => {
      if (v !== null) {
        this.isAssociatedWithFranchise = false;
      } else {
        this.isAssociatedWithFranchise = undefined;
      }
    })
  }

  updateData(value: boolean, currentPage: number) {
    this.map.set(currentPage, value);
    this.data.changeData(this.map);
    this.data.changeCurrentPage(currentPage);
  }

  newSubmission: SubmissionPostTemplate = {
    "submissionType": "DigitalComplete",
    "processKind": "MerchantOnboarding",
    "processType": "Standard",
    "isClientAwaiting": true,
    "submissionUser": {
      "user": "teste",
      "branch": "branch01",
      "partner": "SIBS"
    },
    "startedAt": "2022-07-13T11:10:13.420Z",
    "state": "Incomplete",
    "bank": "0800",
    "merchant": {
      "fiscalId": "585597856",
      "legalName": "BATATA FRITA CIA LTDA",
      "shortName": "BATATA FRITA LTDA",
      "headquartersAddress": {
        "address": "Rua gusta 3",
        "postalCode": "2454-298",
        "postalArea": "Aldeia Vegetariana",
        "country": "PT"
      },
      "merchantType": "Corporate",
      "commercialName": "BATATAS FRITAS",
      "legalNature": "35",
      "crc": {
        "code": "0000-0000-0001",
        "validUntil": "2022-07-13T11:10:13.420Z"
      },
      "shareCapital": {
        "capital": 50000.2,
        "date": "2022-07-13T11:10:13.420Z"
      },
      "byLaws": "O Joao pode assinar tudo, like a boss",
      "mainEconomicActivity": "90010",
      "otherEconomicActivities": [
        "055111"
      ],
      "establishmentDate": "2022-07-13T11:10:13.420Z",
      "businessGroup": {
        "type": "Isolated",
        "branch": "branch01"
      },
      "knowYourSales": {
        "estimatedAnualRevenue": 45892255.0,
        "averageTransactions": 46895,
        "servicesOrProductsSold": [
          "Fries"
        ],
        "servicesOrProductsDestinations": [
          "Fries"
        ]
      },
      "bankInformation": {
        "bank": "0033",
        "iban": "PT00333506518874499677629"
      },
      "contacts": {
        "email": "joao@silvestre.pt",
        "phone1": {
          "countryCode": "+351",
          "phoneNumber": "919654422"
        },
        "phone2": {
          "countryCode": "+351",
          "phoneNumber": "919654421"
        }
      },
      "documentationDeliveryMethod": "MAIL",
      "billingEmail": "joao@silvestre.pt"
    },
    "stakeholders": [
      {
        "fiscalId": "232012610",
        "identificationDocument": {
          "type": "0020",
          "number": "13713441",
          "country": "PT",
          "expirationDate": "2022-07-13T11:10:13.420Z"
        },
        "fullName": "Joao Paulo Ferreira Silvestre",
        "contactName": "Joao o maior Silvestre",
        "shortName": "Joao Silvestre",
        "fiscalAddress": {
          "address": "Rua da Azoia 4",
          "postalCode": "2625-236",
          "postalArea": "Povoa de Santa Iria",
          "country": "PT"
        },
        "isProxy": false,
        "phone1": {
          "countryCode": "+351",
          "phoneNumber": "919654422"
        },
        "email": "joao@silvestre.pt",
        "birthDate": "1990-08-11"
      }
    ],
    "documents": [
      {
        "file": {
          "fileType": "PDF",
          "binary": "JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhwdC1QVCkgL1N0cnVjdFRyZWVSb290IDEwIDAgUi9NYXJrSW5mbzw8L01hcmtlZCB0cnVlPj4vTWV0YWRhdGEgMjAgMCBSL1ZpZXdlclByZWZlcmVuY2VzIDIxIDAgUj4+DQplbmRvYmoNCjIgMCBvYmoNCjw8L1R5cGUvUGFnZXMvQ291bnQgMS9LaWRzWyAzIDAgUl0gPj4NCmVuZG9iag0KMyAwIG9iag0KPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9SZXNvdXJjZXM8PC9Gb250PDwvRjEgNSAwIFI+Pi9FeHRHU3RhdGU8PC9HUzcgNyAwIFIvR1M4IDggMCBSPj4vUHJvY1NldFsvUERGL1RleHQvSW1hZ2VCL0ltYWdlQy9JbWFnZUldID4+L01lZGlhQm94WyAwIDAgNTk1LjMyIDg0MS45Ml0gL0NvbnRlbnRzIDQgMCBSL0dyb3VwPDwvVHlwZS9Hcm91cC9TL1RyYW5zcGFyZW5jeS9DUy9EZXZpY2VSR0I+Pi9UYWJzL1MvU3RydWN0UGFyZW50cyAwPj4NCmVuZG9iag0KNCAwIG9iag0KPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCAxOTU+Pg0Kc3RyZWFtDQp4nK2OQQuCQBCF7wv7H95xN2jdWVdXITxoJkZmoVEQHctTQfX/IS0PdW8Ow3vMY94Hb4PZzKuycg6dJEjnGe6caaWHiSJH0AjiQPkGkSUVGzzOnO0nuHGWtpx5CwKR0hbthbMhrUFwRmlj4YJY2RDttc8VjUP37F+je7todAVnR5Ef5NQXuSQtqkFtZChWg6ghp0Y0O+mLVBJ9rmUjrWjKftVreUK75CzvUbac/QGdXKBs/I3+Jh5B8duHvMrwAojVPsgNCmVuZHN0cmVhbQ0KZW5kb2JqDQo1IDAgb2JqDQo8PC9UeXBlL0ZvbnQvU3VidHlwZS9UcnVlVHlwZS9OYW1lL0YxL0Jhc2VGb250L0JDREVFRStDYWxpYnJpL0VuY29kaW5nL1dpbkFuc2lFbmNvZGluZy9Gb250RGVzY3JpcHRvciA2IDAgUi9GaXJzdENoYXIgMzIvTGFzdENoYXIgODgvV2lkdGhzIDE4IDAgUj4+DQplbmRvYmoNCjYgMCBvYmoNCjw8L1R5cGUvRm9udERlc2NyaXB0b3IvRm9udE5hbWUvQkNERUVFK0NhbGlicmkvRmxhZ3MgMzIvSXRhbGljQW5nbGUgMC9Bc2NlbnQgNzUwL0Rlc2NlbnQgLTI1MC9DYXBIZWlnaHQgNzUwL0F2Z1dpZHRoIDUyMS9NYXhXaWR0aCAxNzQzL0ZvbnRXZWlnaHQgNDAwL1hIZWlnaHQgMjUwL1N0ZW1WIDUyL0ZvbnRCQm94WyAtNTAzIC0yNTAgMTI0MCA3NTBdIC9Gb250RmlsZTIgMTkgMCBSPj4NCmVuZG9iag0KNyAwIG9iag0KPDwvVHlwZS9FeHRHU3RhdGUvQk0vTm9ybWFsL2NhIDE+Pg0KZW5kb2JqDQo4IDAgb2JqDQo8PC9UeXBlL0V4dEdTdGF0ZS9CTS9Ob3JtYWwvQ0EgMT4+DQplbmRvYmoNCjkgMCBvYmoNCjw8L0F1dGhvcihTYXJhaCBTYW50b3MpIC9DcmVhdG9yKP7/AE0AaQBjAHIAbwBzAG8AZgB0AK4AIABXAG8AcgBkACAAMgAwADEAOSkgL0NyZWF0aW9uRGF0ZShEOjIwMjIwNzIwMTMwNTM5KzAxJzAwJykgL01vZERhdGUoRDoyMDIyMDcyMDEzMDUzOSswMScwMCcpIC9Qcm9kdWNlcij+/wBNAGkAYwByAG8AcwBvAGYAdACuACAAVwBvAHIAZAAgADIAMAAxADkpID4+DQplbmRvYmoNCjE3IDAgb2JqDQo8PC9UeXBlL09ialN0bS9OIDcvRmlyc3QgNDYvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCAyOTY+Pg0Kc3RyZWFtDQp4nG1R0WrCMBR9F/yH+we3sa1jIMKYyoZYSivsofgQ610NtomkKejfL3ftsANfwjk355ycJCKGAEQEsQDhQRCD8Oh1DmIGUTgDEUIU++EcopcAFgtMWR1AhjmmuL9fCXNnu9Kta2pwW0BwAEwrCFmzXE4nvSUYLCtTdg1p98wpuEp2gME1UuwtUWaMw8zUtJNX7sh5qbQ+i3e5Lk84JupjRrsJ3dyW7iCG6I3P0sYRJrys9elB9l56NDfMqXT4QfJEtsfs+cOfulaa8rPkhjx40z5BOmX0wK1T39KDX/Zl7OVozOVxe560ZyLHJR3uZGnNiL+f/TriKyVrU40Gea1ONNL253hZZWWDG1V1loa7Jl3TFvzH83+vm8iG2qKnj6efTn4AVAqiuw0KZW5kc3RyZWFtDQplbmRvYmoNCjE4IDAgb2JqDQpbIDIyNiAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCA1NDQgMCAwIDQ4OCAwIDAgMCAyNTIgMCAwIDQyMCA4NTUgNjQ2IDY2MiA1MTcgMCAwIDQ1OSAwIDY0MiAwIDAgNTE5XSANCmVuZG9iag0KMTkgMCBvYmoNCjw8L0ZpbHRlci9GbGF0ZURlY29kZS9MZW5ndGggMjQ5MTIvTGVuZ3RoMSA5MDU1Nj4+DQpzdHJlYW0NCnic7H0HXFRX2v45dyozjMzADG2AGRwBdRAULFgZpSh2yuiAoiCgqNg1lqgh1SyJaZreTDYxxZRh0IimmWzaZtP7Jpu2m93NbmLKpmzWRPiec985iH6a3WT3v/ny/80Lz32e855yz31PuWcMBMYZY1ZctKyuZEJx1QfX1+cwPvZLxnSXlEyYWnT7ORv/zPioVxjTuGdU5uZd/0j9Psb4+ahV17CsfuW796fYGVu6E/mdDaetdR9Y+cYwxm5qRP0HFq5ctGzrO5oRjK2YypjFu6hl48KOZ0eg/G1uxrKfam6qb/xm2sYg2otGe8Ob4bDcnXIY6WKk+zUvW7vhobXOUUh/yNjiu1pWNNRbr9JuZexlpIfPWla/YWVOdMZbyG9GefeyprX115y16zTGi85B+pzl9cuabjjy1XzGTT7GBq9ZuWLN2m4nOw/Ps1eUX7m6aWXcor5JjG3egNt9xEQs9KPev+/RKw/PjxnzFUsyMmH3f7T5GcGvl62f8e2Ro61RHxuHIxnFFEaGenrWxfhjpl3fHjmyK+pjtaVelnSX8DgHslZmZeOYBjWtLJdtYyx2uHpfzjRaL7+E6ZhRd7UuH02mEWteYOcpzMiUGJ2iKFqNov2A5XQfYv1OV3sAm1bpdjM8X8Yz1AfDDUqmm/FukafZr+sjnpTZtX2O9YY/z36UaWvYXf9qWc2H/3rZf2aK9se3pak9eV396+wu3cCT5+mmsoYfcg9t31P3T3M3m/ivtKHry+78Ifc8aT+y2OB/t41Ttq1lN50yr+n4PE3rqcv+UOMf//i2lPdOXlevZzdpLz15nvZOtvCH3EPz+LF2NIdPiMMMVvavtKHdzm78Ifc8aT+eYcP/3Tb+E6Ydyup+6j5E7N835Wl29U/dh5+DKX9kk35MPf41a/lP9yViEYtYxCL24025lptOmVfHDv83+/JzMc0wdsFP3YeIRSxiEYvYjzftIz/s3z5OZcqf2UU9+vZjWhjf3StvDrtIu4xdpFnHtgM1yhu98lpZqWCNnc3u8e1jKf+J/kUsYhGLWMQiFrGIRSxiEYtYxH5e9mM+Z4q0+Kyp+nt93uz9OTNiEYtYxCIWsYhFLGIRi1jEIhaxiEUsYv9945GfRo9YxCIWsYhFLGIRi1jEIhaxiEUsYhGLWMQiFrGIRSxiEYtYxCIWsYhFLGIRi1jEIhaxiEUsYhGLWMQiFrGIRSxiEfs/Yt0Hf+oeRCxiP7FpwkgJ/yWpL5Hi6l+00bI3kM5hbijxN50srC+bwEpYGZvJKpmfBVgjW812peakDkkdljoqdUzquNTx7qiMZ7rVvwiF8u5w+aknKV9wXHne/RXW4/Pdr3f/CTXNLI6ls/t4cnfDR9t6fx3OendsuJ8Dw/3v/8+fUDNZcyUbx4rRlylsNtPzj1X/5yf+7SyklfBf2lLY9xvv1fK/Zzb1Kv9vs7nq9Vhfhc0DmlW18RSdSf6ejl74b/bvv22a/2hr/5/OYV/NeeeuXbN61coVy5e1LF2yuHnRwqbGBfPn1c6dU1Md8FdVVpTPnDF92tQpk8smTSwtKS6aMN5XOG7smNGjRhaMGD4sN2dQdv/MjH6evq5Eu80aYzGboowGvU6rUTjLLvGU1rmDmXVBbaZn0qRBIu2ph6O+l6Mu6Iar9PgyQXedWsx9fEkfSi48oaSPSvp6SnKrewwbMyjbXeJxB58t9rg7eU15AHp7safaHTys6mmq1maqCQsS6emo4S5JbC52B3mduyRYelpzW0ldMdprN5uKPEVNpkHZrN1khjRDBft7Vrbz/uO4KpT+JaPaFWa0iNsGNRkl9Y3BmeWBkmJnenq16mNFaltBfVHQoLblXiz6zC5wt2cfaruw08oW1HmjGz2N9XMDQU09KrVpStratgVt3uAAT3FwwKYPEvHITcFsT3FJ0OtBY1Mqem7Ag7oMq8fd9hVD5z2HPz7eUx/26DOsXzEhxSP2hAn5UjP0DT3E86Wni75c0OljC5AItpYHKO1mC5wh5sv1VgeVOpFzSOY4/CKnVeb0VK/zpIuhKqkLf5/WnBhsXeAelI3oq98Z+Ea+O6jJrFvQ0Cy4vqnNU1xMcasKBH3FEL768LOWtA/ORfn6OjzEYhGG8kAw17MyaPdMoAJwuMUYLK4MqFXC1YL2oiCrawjXCuaWFIt+uUva6oqpg6ItT3ngAMvvfq99qNvZkc+GsmrRj2B8EQYls6Qt0Lgw6KpzNmJ+LnQHnOlBXzXCV+0JNFWLUfJYgwPew+3S1TuqtfBsJ5SWhcWTGzKM7oDi1FSL0YLDXYqLZ8IYZFgxXGpSjOiEMe4AdzJZDHcJlxDquHaQ0GQUTRJZGlG1aJIzvTqd7Hu65Az3SZcRNPZqywpHT5/oPqfsGpUWHRrgLmkq7tXB4xrVhTsYbu3k/VRELMI3Rg2jGM5JMkuTgZULn4JmVJcYxUR3kM10BzxNnmoP5pBvZkA8m4i1Or5TKj1TymsC6miHZ0nVcSnKL6BUkKUjWyaUIszBUq9TDquanqime5KTTsguk9ke0a+2tsZ2pskQU9nZzlWhK7qgOjjDW+0JLvB60kU/B2W3G1l0elVdEdZqKbY7T2m9x211l7bVd3a3Lmhr9/naVpbUNY/CumjzlDW2eSoDY5xq5ysCW5ybxL1j2RQ+pWoCmlLYhHYPP7+83cfPr6wJHLAy5j6/KhBSuFJUN6G6vR/yAgfcjPlUryK8wikSbpEQLVUgYVTLOw/4GGtVc7WqQ003dHKm+ozSx1lDp0I+K90oU72RD+eghk4t5fhkaS18RvK1Uun+4dJG5FhFzkGmiDOkyCRrZyLAPpPOZ/RF+aIVi4KQClcInoMoG8VZRzS3cGc72qxQ3Z28tT3K5zygtlQRLtmKksLX2uNDz0WxXg3hfvTg/mNP4K8JdEQztK9eUWKCMMzCxGbMIbxPStyNYv5trm5uq6sWuweLx1zFNw9yzzgWVDzj0GN9dNDkaZoQNHsmCH+h8BeSXy/8Bsx8Hs8x2GLTbavzYCPGigkwJ6e1phFNuju7u6sC6c86D1enYy3NBWoCwSgvXm66jMkoN1GgDu6JwdaGetEP5g+IuoaMsoZqrEvZIIqUBaPQQlS4BZQoVeuI9YZKDZhr9R5Vwo2to7U6WO0VNw0srlbXqzXIJnlGBfWZ1KYuU9wot7ot1pOnbj5Y66aMbYKi0DdWGSCPE0ncrJqCZIhGzxs8yGqoc9McqcRappeFyUmeJuz52swmFSZnOJOJx9JkmC2mYFQOGsS30OYcsefoMgzV1dR5NbUtXAD3tgbN6FFmr1CGKyA6yCoTfcH3NnRVFH1ENFPeySo8G7B1ik6rLRmQHbRklNXj7Ub1zfB4CmRlo9gEzeE2HiOvQTx5NOKOLaGz+zbPxvRehr1DvP3E/GPOA1iorLrtREdwjndQtvFEr0V1t7UZLSevQPEyWnpYdSoZDeKtABYTTp1v7hLxqvRMbleme1XmKrdN9uANomQI4KCjwfJJdzdWi1Lo8kx1LztlId6rkHhNq423WUfLFA+naDDbgouOTzb3JEsFcBjMyKEzBB5F7LWYK0ucwRbMTFlEjIi7zW31jPKIi1p5okAdBqlnWWD6Y9aJRdPa4A4swGRHg6V1baVt4ojaUB8OW/hOweXe45rEuuCYPGhIPE6wdaa7rtpdh6MpLw+kpzuxGsHuhTineurFq2AmPc/MGvWoUt8mpjjDSaXaGTTgxbSwvsmTjjdIUOxAFH3RR2142TBnW5unLaiu21IURvOZWHZlgvC90uupbxJH6IXiBN2k1i1Fd9XoiNacJR6s5Sa41VgicNj6FohLQ5s4oNfWeREJW1tsm3tkG7bgWrw9tJkNs+rwqhJvJLc61PVOpBCEMpGqRkNUMCpDFKQlIHqzzNtea8g45lG/V3ipsFFtFT2rCARnyiLqehJilTeoJBQgUzw8r6gJyH1KI7LLEF4fZpVT1HYHlapAeHjU+mWiqlMOGFWDR32HhNdXz9tGvofmOhHTU/rxctCMr1SeUp5gBcylPBnmt1mB8ibzK78Fvw5+I8yvgV8FvwJ+GfwS+EXww+CHwA+CH8AHQa3yFhsKVAGaHtUI3AK8AujYUrTEmRn1ObMrj7JioBFYC+wEdCj7EPJuQYucuZVz9kYl8skY0LOlOEuKM6VoleIMKbZKsUWKzVKcLsUmKTZKsUGK9VKcJsU6KdZKsUaKVVKslGKFFMulWCZFixRLpVgixWIpmqVYJMVCKZqkaJSiQYoFUtRLUSfFfCnmSVErxVwp5khRI0W1FAEpZksxSwq/FFVSVEpRIUW5FDOlmCHFdCmmSTFViilSTJaiTIpJUkyUolSKEimKpSiSYoIU46XwSVEoxTgpxkoxRorRUoySYqQUBVKMkGK4FMOkGCpFvhR5UgyRYrAUuVLkSDFIimwpvFIMlGKAFP2lyJIiU4oMKfpJ4ZGirxTpUrilcEmRJkWqFClSOKVIliJJikQpEqSIl8IhhV2KOClipbBJYZUiRoo+UlikiJbCLIVJiigpjFIYpNBLoZNCK4VGCkUKLgULC94tRZcUR6X4TopvpTgixT+k+EaKv0vxtRRfSfGlFF9I8TcpPpfiMyk+leITKQ5L8bEUH0nxVyn+IsWHUvxZij9J8UcpPpDiD1L8Xor3pXhPineleEeKt6X4nRRvSfGmFL+V4g0pXpfiNSleleIVKV6W4iUpXpTiBSmel+I5KZ6V4hkpfiPF01L8WoqnpHhSiiekeFyKx6T4lRSPSvGIFIekeFiKh6R4UIoHpLhfioNSHJCiU4r9UtwnxT4p9krRIUVIinYpglLcK8U9UtwtxV1S7JHiTinukOJ2KW6TYrcUt0pxixS/lOJmKW6SYpcUN0pxgxTXS3GdFNdKcY0UV0txlRRXSnGFFJdLsVOKHVJcJsWlUlwixcVSXCTFdikulOICKdqk+IUU50uxTYrzpDhXCnns4fLYw+Wxh8tjD5fHHi6PPVwee7g89nB57OHy2MPlsYfLYw+Xxx4ujz1cHnu4PPZweezh8tjDV0shzz9cnn+4PP9wef7h8vzD5fmHy/MPl+cfLs8/XJ5/uDz/cHn+4fL8w+X5h8vzD5fnHy7PP1yef7g8/3B5/uHy/MPl+YfL8w+X5x8uzz9cnn+4PP9wef7h8vzD5fmHy/MPl+cfLo89XB57uDz2cHna4fK0w+Vph8vTDpenHS5PO1yedrg87XB52uFFHUJ0KueE0sa5cGYOpTlAZ1HqzFDaKFArpc4g2hpKiwZtodRmotOJNhFtDKWOB20IpRaB1hOdRrSO8tZSag3RanKuCqVOAK0kWkG0nIosI2ohWhpKKQEtIVpM1Ey0iGhhKKUY1ESpRqIGogVE9UR1RPOJ5lG9WkrNJZpDVENUTRQgmk00i8hPVEVUSVRBVE40k2gG0XSiaURTiaYQTQ45y0BlRJNCzsmgiUSlIecUUEnIORVUTFRENIHyxlM9H1Eh1RtHNJZoDJUcTTSKqo8kKiAaQTScaBg1NpQon1rJIxpCNJgayyXKoXqDiLKJvEQDiQYQ9SfKoqYziTKozX5EHqK+1HQ6kZvquYjSiFKJUoicRMmh5OmgJKLEUPIMUAJRPDkdRHZyxhHFEtkoz0oUQ84+RBaiaMozE5mIoijPSGQg0oeSZoJ0oaRykJZIQ06FUpyIqcS7ibrUIvwopb4j+pboCOX9g1LfEP2d6Guir0KJVaAvQ4mVoC8o9Teiz4k+o7xPKfUJ0WGijynvI6K/kvMvRB8S/ZnoT1Tkj5T6gFJ/oNTvid4neo/y3iV6h5xvE/2O6C2iN6nIbyn1BtHroYTZoNdCCbNArxK9Qs6XiV4iepHoBSryPNFz5HyW6Bmi3xA9TUV+TfQUOZ8keoLocaLHiH5FJR+l1CNEh4gepryHiB4k5wNE9xMdJDpA1Ekl91PqPqJ9RHuJOkLxhaBQKH4OqJ0oSHQv0T1EdxPdRbSH6M5QPPZrfge1cjvRbZS3m+hWoluIfkl0M9FNRLuIbqTGbqBWrie6jvKuJbqG6Gqiq6jClZS6guhyop2Ut4NauYzoUsq7hOhioouIthNdSCUvoFQb0S+IzifaRnReyFEPOjfkWAA6h+jskGMh6CyiM0MOP6g15MBmzM8IOYaDthJtoeqbqd7pRJtCjkbQRqq+gWg90WlE64jWEq2hpldT9VVEK0OOBtAKamw5lVxG1EK0lGgJ0WKq10y0iHq2kKo3ETVSyQaiBUT1RHVE84nm0UPXUs/mEs2hh66hpqvpRgGi2dTdWXQjP7VSRVRJVEFUHrL7QDNDdnGHGSG7mN7TQ/azQdNC9kGgqVRkCtHkkB3nAl5GqUlEE8lZGrJvBZWE7NtAxSH7GaCikL0VNCEUWwoaT+QjKiQaF4rF+52PpdSYkK0aNJpoVMgmpsZIooKQbSJoRMgWAA0P2WpAwyhvKFF+yJYNyqOSQ0I28WCDQzaxNnOJcqj6ILpDNpGXGhtINIAa60+URZRJlBGyiSj1I/JQm32pzXRqzE2tuIjSqF4qUQqRkyiZKClkrQUlhqzzQAkh63xQPJGDyE4URxRLFWxUwUrOGKI+RBaiaCppppImckYRGYkMRHoqqaOSWnJqiBQiTsR83TELXAJdMQ2uozGNru+gvwWOAP+A7xv4/g58DXwFfAn/F8DfkPc50p8BnwKfAIfh/xj4CHl/RfovwIfAn4E/9Vnk+mOfZtcHwB+A3wPvw/ce+F3gHeBtpH8Hfgt4E/gt8IZlqet1yxDXa+BXLS2uVyyZrpeBl6BftHhdLwDPA88h/1n4nrEsc/0G+mnoX0M/ZVnietKy2PWEpdn1uGWR6zHU/RXaexR4BPB1H8L1YeAh4MHoVa4Hole77o9e4zoYvdZ1AOgE9sN/H7APeXuR1wFfCGgHgsC95o2ue8ybXHebN7vuMm9x7TFvdd0J3AHcDtwG7AZuNQ9y3QL+JXAz6twE3mVe6roR+gbo64HroK9FW9egravR1lXwXQlcAVwO7AR2AJeh3qVo7xLTdNfFphmui0yLXNtNt7ouNN3mOleT4TpHU+A6mxe4zvK3+s/c0+o/w7/Fv3XPFr95CzdvcW6ZsuX0LXu2vLXFF6s3bfZv8p++Z5N/o3+9f8Oe9f6DynlsoXKub4z/tD3r/Np19nVr12m+XMf3rOPF6/jgdVxh66zr3Os00Wv9q/1r9qz2s9UzV7euDq7Wjg6ufm+1wlZzU2f3oY7VzrRSsG/zaou1dJV/hX/lnhX+5QuX+Zegg4sLFvmb9yzyLyxo9DftafQ3FCzw1xfU+ecX1Prn7an1zy2o8c/ZU+OvLgj4Z6P8rIIqv39Plb+yoNxfsafcP6Ngun86/NMKpvin7pnin1wwyV+2Z5J/YkGpvwQPz1KsKe4UjVV0YHoKesKcfMJgp8/5nvMzp5Y5g85DTk1sTLIrWRkQk8SLZiTxFUlnJF2cpIlJfD5R8SUOyC6NSXg+4d2ETxO0cb6EATmlLN4a747XOMSzxU+rKlW5sJh4yDD1WV3xnszSGAePcbgcSsmnDn4e03A354xbQRojyuzlDlep5kEufsxOxzi/hFV5p3QaWcWUoHHmnCA/P5hRKa6+8pqg/vwg89fMCbRzflG1+jMJQbv4oRI1fe727Sx1wpRgamUgpNm1K3VC9ZRgq9A+n6q7hWYoUu2dt2bdGm/AN5bZ3rN9ZtM4HrY+b1ViYnhMTHeM4otB52P6uPoo4tLdR+PrM2REaYzFZVHEpduiifdZ4BHPlxU9s6o0xuwyK/5C8wyz4jMXFpX6zIMGl/6v5+wQz0l39q6dh8u8NWu96jdS1XydSHqFV3yvWYu0+Fqnppn3e42Kgeavga2VzrXfX+v/uvGfugM/f6Of5BnfrZzDGpWzgbOAM4FW4AxgK7AF2AycDmwCNgIbgPXAacA6YC2wBlgFrARWAMuBZUALsBRYAiwGmoFFwEKgCWgEGoAFQD1QB8wH5gG1wFxgDlADVAMBYDYwC/ADVUAlUAGUAzOBGcB0YBowFZgCTAbKgEnARKAUKAGKgSJgAjAe8AGFwDhgLDAGGA2MAkYCBcAIYDgwDBgK5AN5wBBgMJAL5ACDgGzACwwEBgD9gSwgE8gA+gEeoC+QDrgBF5AGpAIpgBNIBpKARCABiAccgB2IA2IBG2AFYoA+gAWIBsyACYgCjIAB0AM6QDu+G1cNoAAcYKyRw8e7gKPAd8C3wBHgH8A3wN+Br4GvgC+BL4C/AZ8DnwGfAp8Ah4GPgY+AvwJ/AT4E/gz8Cfgj8AHwB+D3wPvAe8C7wDvA28DvgLeAN4HfAm8ArwOvAa8CrwAvAy8BLwIvAM8DzwHPAs8AvwGeBn4NPAU8CTwBPA48BvwKeBR4BDgEPAw8BDwIPADcDxwEDgCdwH7gPmAfsBfoAEJAOxAE7gXuAe4G7gL2AHcCdwC3A7cBu4FbgVuAXwI3AzcBu4AbgRuA64HrgGuBa4CrgauAK4ErgMuBncAO4DLgUuAS4GLgImA7cCFwAdAG/AI4H9gGnAecyxrHt3Ksf471z7H+OdY/x/rnWP8c659j/XOsf471z7H+OdY/x/rnWP8c659j/XOsf471z1cD2AM49gCOPYBjD+DYAzj2AI49gGMP4NgDOPYAjj2AYw/g2AM49gCOPYBjD+DYAzj2AI49gGMP4NgDOPYAjj2AYw/g2AM49gCOPYBjD+DYAzj2AI49gGMP4Fj/HOufY/1zrH2Otc+x9jnWPsfa51j7HGufY+1zrH2Otf9T78M/c6v+qTvwMze2Zk2vg5mwxPniF4UMNzDWteO43x2ZyZawNawVX+ex7WwHe5i9xRaws6GuZrvYbnYHC7JH2K/Z6//6r9X8c+vaqFvGojX7mZ7FMdZ9pPtw126gU9enl2cHUnFa9zFPt7X7kxN8n3Tt6LZ2depjmUmta1FegvcLfrT7CF65SHcPF2llG3SMWuNzww1d93bddkIMylkNm8PmslpWx+rx/I2smS1GZJayFraMLVdTy5G3CNeFSM1HKWwvqj5WagVbCaxma9k6dhq+VkKvCadE3io1vY6tx9cGtpFtYqezzWxL+Lpe9WxGziY1vQHYys7AyJzJzlKVZPKczc5h52LUtrHz2S++N/WLHtXGLmAXYpwvYhefUm8/LnUJvi5ll2E+7GSXsyvYVZgX17LrTvBeqfqvYTewGzFnRN7l8NyoKpH7AHuC7WP3sHvZfWosGxA1ioiMy0I1hisRg814wrN79Zjit74nWlvx7OLZ2sJPugH+s3rVOC0cR1HybJSkVmgcRCtbTojEJXgG0seeiFKXq89/zNs7Kt/nlfG4rldkrlVTQp3oPZW+gl2PFXgTriKqQt0MTepGVff239BTdpea/iW7hd2KsbhNVZLJsxv6NnY71vadbA+7C1/HdG9FfA+7Wx25IGtnIdbB9mIk72P7Wafq/768k/k7wv5Qj+cAO8juxwx5iB3CTvMovqTnQfgeDnsfU32UfpT9CmlRilJPsCexQz3NfsOeYc+zx5F6Tr0+hdQL7CX2MnudW6BeZH/B9Sh7QfcB68PG4+P/QcT5OjZP/S3K/2emS2YOtqv7m+713d9oJrGFvAoHyLswSnvZhfjEvvxYSe5iJu3vmZ3t7f5aMxfc/+ibuuaum7s/ZTrsmms0L2GX0zADG8mmsensyuC53sADzIJTSjwbxfftcxQXGwcZHsIJRGFunGGMjPMiX4xWsexPTi707B+m366xlXXyQXsLDdtxOi88+s7R53KPvnM4dmTuYZ779vvvvG/9/DnbyNz89195f8hgp8+ebNnfgqrDPPtbhmn021s0tkJR3xfVUuhTDNtb0EhioTf5Oe9zud7nvGjGO3hINbel21TY+ygGg13v6ZujDMvKHJ6fnzdOGTY009O3j6L6hg4fMU6Tn5emaOzSM04Raa556bsazYyjemWrp3BWvi4tOcZu0euUlMTYQWMyrJVzMsbkpBo0Br1GZzT0HzGh75SWkr5vGmypjvjUWKMxNjXekWozHH1L1+fI33R9vi3Stny7U6MfPbewn+Yqk1HR6vWdaYlJA0enl82KibNqzXFWW7zREGuL7l889+h5jhTRRorDQW0dnYaY38WYliP6aczLCtjfReR9ya5EK5/mssaIiwWXxGhc3GZcOpUcX/9khw/5Dh/yHQ5ztiicLQpni8LZonC2KJx9EB/1WPehfdAsM7+z+8MOlAR/1hETZovKX3dEq/xhh1mwYvVZdpkPmRVzctaXQ4YY+qn/Il0+tJOb2w1VrPBwoTquI3lu7fvqISDvFS8JMU7ekaTFMJuSh2R92YImrKKNvS3WcoNoJdSCZjC8hWqFkWJk7X20nvS+mcNsQ4fnp2OgHGKI0zR8aI7i8djE+MYdk1ruKpjRsKqs656EAQMSeObanQ158d7xA4fNLenfdTS5oGZy6LGiiuFJ0zMmLi1/7sjoQFEmXzN2UcW4gQ5XlvasLFd21aZpOVUTC2JNwyqWKzx36rCUrlrP6BlH3x4VGOPqKkgZUSF+2xpjo9mMsclm94hxaU/OCscwKxzDrHAMs8IxzArHMKtTsfmiouLccW4WxZI7udFnac3khzL5C5k8M1OfJP7h31KeBWrX90S0dtVqLJbc2JEjc3Ot4cgiiu2ZagPmFpbJ4zWobRHV97ZYyvWigVCL/lgw58+rFQslQ0z7E8PpSbedIDWbtSaL8egOEUVlodFi1Olw6dLzkNESpdVGQU9XuNFi0k6MdcYaKXbGWKc91mkzdi2JsqbExSZbDV1DjDanGq/uIzygs2NXqhfx2l+YMCPh3gQNC0eNhaPGwlFj4aixcNTYQcXGTN2H9jv4NJO1QudnhYU81yunU62zQ3UmFhbKRxQr2xZe2g4eMNrTkxL72o1RjvSEpHS7MdkYbdDpDNFG7ZtShUd1CnqZTL08wBzUPUe4e45w9xzh7jnC3XOIn5RlUTEVjk7uDQ8bz322Z7Z3xFToRVbPgBw/EOFeUuCnILhRRx9LGGC0900UXeUvwKGdYnfGRSHM98jufntTlC2FIqv3YiaOYa+pO4S1btzKcYpl8OCE3FxTTmJicjjEyeFnSA4/Q3L4GZLDz5AsJmZavyHR0Saxa5jErmESu4bJhFKmRBQxiVHAruFLEkPSb3i5OTHBkps4JEfv6l/u8sf61XEpLIxNGGnLRwDk2s+z5Vt7lG3k2Nz8fFu+GDWf/aRtJB5r5Ljh9PA+GqGyuMd2bIzFHp+mJPB8jo1dDaTea7S7khLS44xKV77G7Ei1O9LsZqVrIjfa3UmJ7jhDtrPZPbhfYhRfr+PnmZNdmUnLYpxx0cdmxaJvdxpMBo3WYNJjI7+6x797YL/o5P7O72ZrdqcNTDJHxaU6aAy0W3U2NpbtFmPQkRUTYw+HXeWYMFtU/kyE3R4Ou10Ne5opJydPhD0vMUZcUDDPGi0UiuSJIlaWVlBhyonJ0ib1LU/yizmmxkiE+X9FOTdfbLF9TqiQGK4hY0qhzMzM8sTHO04S0DRNQn5mr/mp3WpxJFtGJGd5PI6uZvf4FEVRjHGuxERXrDE7uSI1y5Vq46NSh+cNSeTYG+JcSfHuWONEO15t5tS8LOW9kVtGT7pi8ndfGCwimhaD9s7+fU0JA1xHnxraUFebO2PPDOUhQ7TYXqIN4vckuw9rP9Sl43NXFrue3n52ESO7mJp2uwhmrIhkIoUx3xflZoPxSUXD0sLBTwvPefDHIvjgT0Tw08LBT7tfyWcmlsQHhGIqPWLt6mapWy7PpUi+UtuzhttjsLcO2NsSU6nzqEsZRdW9ld5Rx50lDOKFhBOHw56mqG+lDyfveGfnZa9eUDx55zs7L35le8m+rDlXrVx51fwBmTVXrl51zbz+yhXXf9c+f/bur3ddfeTe+bNu/eKO5Q9eML3qwvsXrT50wbSqix8Q/w8QzDPNk1jrKWwAu1F97/TThx9VH35UfXh568PLWx9+VL2YRAm2VBHAVBHAVGu0hU9NFaeBVPFjZ8yW0clNHXp9NB7P3OEojxaLOXxMoynW+82jF6X3taC4Q5Tf26JWwBTrOZGpU+y4aYX9TWs49q7WPOlbf/eGHVFx6UlinxuYzB0Dpy1eNnXAvtGza7NvvHb6otJ+mh311y0f05XTswAxZQwJhXM3zp6xZGifo//oP7EB629i92FNA2ZKGe9P+/b47g/3xlj51PHhaKhsDXO0ympUxncq2T5vni/Ozqfm+Wx8Wr+8fnnRzkRR1yk2P6fVKi6o4hTTzHlQGSJ2wA6n+m461JEUZjvxfTE2PpVF59zPs9gIZuKZPrPNPYKP8Jmj+VSb+K9pJqFG2EbY4sfgDb1vvFM3oDIeEys88/CGP2wTb3mvt9Z62CpCL0Iuz1BqxrEpOSJH/IxDi83UyTP3t6itDhDN7m9R29WJhnsmKmp7w00fm7JaOWXpnJyjD6f1jvDAhaexXtNQtP6m2vErZo9OMGuN0cY++TNXTS6oLeqXV7F4eXNF/ujFl1Z5Z08bE6fXKhq92WDOLa4dNXzm0OS8yiXLl1Tm86VzLsJRzN03McOFA7Ohb39P2oiZ+SOmjx6SP65q1YzyM2YNiklyxZltiXGxKXFRKZ7U1METMoZPH5OXP7ZylThD3In9YCPezl62T90NUusGcbeYz24xn91iuNziXeUWIyV+Z8VnYz4cGJgvTlwwuiw+vFriw6slPjw/4sOrJT48L+IPKlZx3ugQ5w0xbFFowpRZYa1wHhur/2HvW8DbqM5E5yFp9H6/ZcXjlyzbsi1LdhLHTmL57cSxg+04r0IiS7ItkCUhyUnMQmpCCJSmLWyhXFp2G/piu91tCSFsWiiYjUvpkvTJdum9pQ190HbvDeV2LzS0iXL/c2ZGkh0nDb3f3q/tav545pwz//nP/zr/f86MFKEVCG+MV+rqChYjJxGi2FGo/I2FUSKf8fn4UBBj53rmT83e8sTBbkhVdmu5QeoZnR3YPHtDHV7BlBlk5I/2fXm+c8Pc0/vpCmFWXPzNriM76z07Dm2nLbnlDGjMC/HiHdBYIzHEaaymkaxpIF1W0mUhq82kmyBrRioUOueIjs/d4CQbm7zkjfhwdCgKb1v5+yh/mM0SCZc/cE52uVavISGVrF7NpQ6Uin2Aw5D0z1RifU05W2lSiLLnsq+JlabKVWUujVhFBrNfUjJa8AOXWS4hzaRRLDeUO0urdSJl9okNZrtGTEsVMoq+dAnyAS3W2M3UKLXR7NCIaAbWnyXkz6QqaFc7zJe+hv6fnsfg9GkRy++XJnF8dPmfoWhCQZRS5hNoQ3SKWg+pFHYvP4GtR9Ub2rD/bWaqcN/yyutQeF37uo/bizZV/wRvUqreiGnDjP/tGGBf1/aEXnF7Qn+6xN+zLRTInjZWVhpJ956D4x5D5eqKui2t5b821fe0f/5ka8BtanOsGe1+7kct3X4n6W8e7/GVa51l9GfKnOXdoUB197p6tbS2awf58Yp1bnP2eUd9e3ZzXWeDNfsZc90GlCeQJi6CJvREKbGB27EbqFbY7dspI2w+rO+qw453xVNCquM23kq19d2YOix2vBsTTy1NbRUF8hUG8IsD9730od9jUXT3vXBX9xPubffEHrh/8shOD1V69MyRAMd1z+HnD44cnVp38c2myMPILxF/auDPQ+wQdk/AmFEGmyIDIbP/Fu2DLqjC1RckedvAeprb/WDLGFz238bwhudCTBWWVF+ISQoM8x72OWoRo5Bc+gWSgdIzCkYEdSa7l5xiFFIa/I/JPkI+DvFM1K236xhOHkbr0OttGmn2DKO1G3Q22Od8ltHasGSwz9kscsE+p5LLRARlfEqujYin8Y4FKfoErl11q7IZr1EhH8qMrNXGGqUWgSv6PyRcScLrkPoBjGQlmrmRDDASwagixlOk+rhoStiDoBFVERFqfTImmspvPyQr7D6oH2g12VJjJQQbPDaZQDm3p7IMBD8jjH7xTgY2dVhWcQSsuJa4GXHwlMdUX209RV7ukJWrGuX19eXNclTTEeUt4Xqzgna6ws5p7TRWRX7t6tPDhgDCChgWshOyrWY5urAfWL4bEELQNXYDZpM4whhYi43VM1T2g6IKt6lEL6Ozj1CMnrXZSvWMyxor9ZTBVqBGRPqUtrKakklbZV7n+y8eVippiUxC337xA7nWr5ezaBtwqZl6aVWtXcGW87an3wKLtBGD2KvL9OhD0CUi7yny5Q4VUbI6oqi1sGHLND0lhFqsAN6lFYX3C2MtWAomILdSN+KssVxag9ls8TfQeWPSb5Xb06UubfaX7mEI0RTJ6ErMVieS9nadwwhb9LptNRQJh0RfYrE6dZLOcra0jFJs/vhg+abNm8ovPVcoq1Rj1WYrb3hsxL1t27ibfBvyvwgtAlCsmbz8pqhb5MOr9H4k9/OEkWqDWLMKzmhtrXlSMwlLRM1xcXRJwMELag0sqCfRgloDqTJ6/Qvq7sD7n73ttn/6q/bO+Wdvmz15e8eTZZsO7Ngxt7mC3QzX2wbLqFWHvvXAUPc9/3Lk4Nn7h7qPvPiRHR+NtXckPnrD7o/NtHUmH0JxEix2M3iwEzLGEJcvJM9QRkIHzLeDyXTVb4vFyqp3TGHldOFimLeYRlz9dgwQTFXvxDDKH1r+mi2raKbZVe1yCRH05ubQRyIPClMeErOqoptdt7uj/ETnBlOj+a//tm2gyUb9fPTQ7sbsA4UmkTBK/1BkU/+ETizOzpSu2Uzw8jwK8viJDiLMRQU5ZXqqSVuna0ZfUHG16VCg1ZTU6d5oa7O0voO8jZuPQv573YcyYOv3cUrQ17Xp3ogBJtv6TozHRZ6Zy37CbKyubqCvXOwLudBiMZsL8iH9qNRUVeIoM8npcU2lN9A8JcgPecS+9+7dXmfLYJOjvqpMu1PO/C+Td3PHQx/eMOSzGRiYhrRMrfhNbXejPTuc08fLZU5X71QAZUqtoszb4f6V3Ub9qKK9zpb9oq0R/X9CA5ffpC6Cl24mDnN66aT0J13Nrma1E30fh1DDJFV1yFo3vOvsEtdNQuDSPc0avAbKABFNhV330is34vX5pVfOc8sEyEbYj1txX1WstW7DuzHc3YD6n4gZxKiz4NiL3BJ8scC/Jde7+qYutk1+eNS/Z7BFy4gpCnKTor432F4/uKa0rnfXjbv6apvfd3t/7UhXkxrflzGymvUj/uoOj9XTt+umXX0esnpTZtijd5RoFVqT1ug0ypwVTnNNm6tmfWNVrb8nGOiIbqrRmm0aWIFrDXad1O60m6r8zroNDdVuX/dNKMJ98vKb9JsQ4eqIDm5VwVIGmOlmynhS7opoI478NN8oTPOT6AZaDOdn+PUuhuk318f/dmLPo4l14CBWe5lBWtGzp7X1pu4yqYG1OksNDPnxzMPRtf7IQ++nkkJ6uvRoMNJdDiulHVQilzBJYjXMjY8C735iluO9klpL2Ak3RXTIfTa/zw5AqNEXlKxK+SmqDfKWknW5lPURl9JQGjHw8wRHbVujv9Fu1b72OvzDfoDzlxbPGUVhhxWXzHQ1Q6+waDZY1hjyy+Y7NbS+prQUlsbinysUPxcpjBX2UreeVpOe7E+VYr27wllukot/oFG+IpIbID+7NBJF9qcb7FYVLJuVUvIOiyV7FxRoscpqJV8jXzbb1bBwVkqzx+x28iYZ3JGo7cZsK8SNvbB/flQ8Q7iIVuJZvFMo3dhGKhytaE/VivZUrWgf3Ir2Wa1od9X6DPkuGL7x8jm0e2rkd1WN/K6qkd9lN/K7qcZTlLwDmOxVtFY7ROpa9FF166bmU6TohHqLeBBFVog/eD3Ab6f4Bw2t+CGhXOhoRT2filk3qVHfp2K4M4q5EJCWrQ5aOF1z88lsybuUy1WYR9bQj0JmNKK3L32P7A4d3e72TTywZ/iuDsZYCgsgvexzXXd0b9yxxmZqHg+Ure/orbbB/gpcSindv2V8y13HJzLPHO7r6aIUwjOtSz2j29snbu/oPhRZr6/tagLPe+Ty76jH6X8BzzuC10nJFtKl4TecGl5FcH0LP7HQ8DtSzSnyQoe+YOvKosfidggsVR2yuk0ujYkdMCHVIfeCgLQo7ECxzo7XYUR5LI9p5VALsyvSBKO7YiKa8AsyCfU4JZFJpRZnpcnmbVlXIdVzz07RisHs1DJVgXWtTlVZpVMpokl6wrxKJ5PJpMaGwTWXnpAq0AIBVtCHYQcHIVshvWt1d7WGlsrlMrUDPK6f+hp1m0RHVBItxC6klSdltpZnyB3gVPXkBzq0utIZm4x2P2G+1fcJZYZO8z6Cl0wQV3x4oWjASGb3EzHzrUrfJ2IYkfcHbtKR/JvA63KH1Wuo22xlOrNG0hhs79zdamcDezY2jbgZjd1otGsl97r73JXNpRrlKp+rcqCB+plSJYKFYaCxqXE42t6bHq5zucgGsVRE0yKpODva0MA2d1VU9raU1bWg6BmjXia/I3YQ9UQvfkpcbifAyts7lHb5YvWt5RrTqqQpnbfo/17UYylV1fLFWP7+ddhxNVr3clYUkd+hRIxYqtCYdJoStsIs1nLC2CoqLNZaV4VBXWZmRKTouzorpA6JWGF1O7N/B2KJkGyUVQlHX6nbIhVJJWoLQZHyy++QPxTfBDucGqIKyXFSXOXYou0Fxl/7JvD7tLiqA9eBUftr3ywM9bSLV7th+bvXrzLo3WeJntGRUlNFiaPCJFXLbO7S0horbFchDrptMnJWWHbSX1HqlWKJUqf8fWtZnUOhcNSVldXbFApbPVoFnb98nvySaA/mcC0X681UmGAJE9X6tEJbC/xCinrtm9pFIUc9jRo7HCg72VF7AdPVdPPVmH6I0ThMZodWQuokhsoSRzmsT2TmSmeJyyKTWVwlzkqzjGxBrxFoOFGXlVq5WKzQKC+yzmqrQmGtdjrdNrnc5gaeP0hPUh8XzxZq1eHq0/aBVs/6sFYdHbiOtHrWt0Srwhp5WYvZRN0l0Vr0eqtGYpEbyyywwpKR2XuWtHld9BFBreS3hFK2aWmbVksQWmKS2CXaLRoiGEJDWIhSWO83EmuIjUQfMUxsJ/YQU0SC2E+8n8S7n4741unYWGztgdvbb3cnM54MuzdcGZb2DyoHiY5uUbfW22xsjt2eCQ92Nzd3D4Yzt8eYkh3vs5ZsSu0b2td528Heg76b46vj9l03rbpJPzJuHqfWbZBskNc2qBv2HYzfNL6hoWHD+E3xg/sY1+REuYtoPNt4VmeBXIwPnV971nftE4l66N9LDzQb1/5x/HXARr3R/l5ZxGauKG9p9vuq+auBv1r4q3CfWVZffl1+nzEvrVctoy+MR7/ibW72PohOv/U3+ZsqUSm7xgfHP/qbmvzUCDpfsqMG6q4c7qUvept9vkqyqbm5ifw6upl9Hzr/FmE/iEr0x+DkhVr23/z+ph9DhXwYCuOI2l/Bifyqr7HlUj+UHvJ6mymWR8oyUPgl6vaDZm9zAxQuXyY+TH2b+qT4Z5REepIgcP071A5cP8XXz5JW8a+g/mzufkD871B/nq9/i/6x+JdQX8D1D1FnqV/i+gu4vot6iXaI34T6aR7/Zeogpv819BEaohey2Trxr4keIs7tLtrJHScrmyqbVPZT5D2wkVRp/Bq/pfV4u11cc4o6csJyXJxZ8rgfdhTn8UryPA75GL2m9XiM73BSbDkegy5LnuPngoALdl/IVmh7CWkMNhIUbuHiAmy+TEaEhHKdBKU6QKPW1Q5E2tpvLFHrZbRFYVcqSqu9zrZ+i8vvqOxvq6zq3LXa0dJQqZBLzUqLwrihfnWLpdpXUrlpXRV9onXn+lKHVqrWmnVdOobRauRtzfbqVXalztWyeXXz1tUlUo1BLjcbu9VihbPFZXeV2uDe6k2gu+2gqy9iW7yEdVcCunxE/AuIJSNId09bG6wNhBmEvvtphaWxQqSDDdrdJ3RpcTr/xnMRiQ+K+jJRswJawXtOMr/ozi25DXR+yZ1bcNPUYaVMWVFmsWukos9+TizT2ExsmVyu/N7LSrmiosxk08olf/M3YqnaaiqtUMpUL9Mys01J0xI5QzqyP2fkElqsthrJbeSA0QZLcNiiZd8lZbD3oGHhasp+BT2h5v2Uf0J9AK8C7ITL/xy5HT2jJj8A8d9D3tehJhR21+K3faTPJ61a1CDJ/IvSVO7TIPhB9flXzmsvLerwGkFv97kWY4SPNNPQRVO1GEOdTkr9izHoVvgRkNwza+GZrn/5M2tT/pk1LlKfNFT42vs839XY7OpT/TeuZ9V2t41d67Y+q3J4KrbvYd12VYO+crV7+uCqunIDfbxyg89lVxms1HNWg8O/ubHEX1ehkLC+LrLVVG5VntGX1ma/WlLn1LyudtYgH+DnK+Hhn9rbq0+ROzu0Mvw0eJH/YMyiCumhelFSoAey8bVXFkELSAc6l32x4IMwizGEf1JSvRiTLFWBMG+ufDpsEpQBouPHoTtoiUyc3a9xONTk3WKZmKbFjDj7g9/BGRd/R3rEjISmFRqzmgGBv2o1MBqLVmPWMC9KlVa11qqWvMFoLVhGHIPAwrXcmoQgdxFyQkvdfRy7Nomn/peFButVdsmkVaJ1GPSrtBKJdpXeAKsP6pyYQUtO2Pi/I5R4nUKMgy0ufj58nCGfIXdCFjeDEslFVYp7Pnz+LB4UGk+qSFBZSng+TBY8KS94TExaSBOWGOnlwxqHVOMwAhNi8b9dSoOcOl4P/4NnBPOBYyvRRuzFfNTb0NfdK7xydCEqWpCRGiwKepUblValhZkuPCA+79Oe92EmW1bCLHw2nNcWzX9QhK4wFC6LuUnvNwgfFKF/zGhtJoNDzfyKlIHRtGa1jPwhSTJaK7RqmFWGXgtr00q+QX+P0Zts+k1yg1JG/RSEgwP03XHpWVoipmiRRATl07n279tNQEJ36TeUSm/XSMRKnQo0wWcVYj0xhjWh8KOv+q93G58ht0FIWAuG0TTYypGX24Rwhzc8532v8Cq4AqfgAQOZ+0wHfdXPdBjwZzqa8+5E/VIGGcCld1itmu9oKw2kiGLUsEOAzcAq3Vqjw2RUPKYpsdt0pBi2QSatXcNQF5U6hZjRlVrJe53dnuYb3NndwqaHetVqkqhthux3SiDC1vu7Ssl/EOYKrHL5PArrxwqik5sFWvI+9F6K/OAJqQnN8CMnShe53AiTG0IciP2UyoQnM2TB0kUhC+b3Py5+V7f8GTHtqN91z64nH0fnL37hI0bv1rb2rT6TwTvc3n6DzyQK7flvN687+883fgzOX2uf3FxbvyWyZv0Uuk4Cr3yOx5+1GOM/a4FmkI5wQoSWE7rKRfRZiUUT2OK4Ml3wePg8H5CUkspF7gMSizEB69pPiP1LPyBBHazqm+gZk6rtJiMo3q77e4c30Ndo+7Czrt48NOjyl+tFlzaEeqqzv8653qs2o0jtWruppcpvZbIXTVXN4Hl8zoWs04MkCcgJFiSpI8xwVhAu6m4UdU44eMVvFBT/jHALNiM5xWNX46bXtZ7dUV+kaodu7QvEBj0SbYlJDzHCUtfmqm6rsYh1doOxRC2l/6M/OVxdtSnRT/674CTZ9uYtzXa7b9BHfiPnOEt+F0eJJHDg086dXrh3+SvMRygv8zbkV+lxMFyj39tEl5nKeql9l+5j3p6EPs//ISA/tBJQVdcFB64J380D/aBoYwG8tDKIxwpB0rcCnPtDwGx/T/DDQpB6eHjkuuCb1wKZpgAelusLIHkVeBWBIsKBUroCTP5B+D//76D69F8+qOv/BOHxq4NGXoQi/IXA7iVw8k8HtEwRivCXDbqx64D3YQjzEMOQ0d2uO6w7qnsQgb4WwIfh74pQhCIUoQhF+K8LhmYMn+PhRwiM5cbHTW6AgwA/Q2DuKUIRilCEIhShCEX4M4fRIhShCEUoQhGKUIQiFKEIRShCEYpQhCIUoQhFKEIRilCEvwAIF6EI/3UBfxetnion0Pe64aC0uIXG32lX4xoqU4Ra9ARfpolK0XN8WVSAIyasop/wZUlBO0PsE/2OL0uJWvFBviwjWOYQX5ZTx3L4CmKc+RRfVhK1zAW+rFJLpAKfamIT4PDfpyOlZjdfJgnG4uXLFMFY5/kyTVit9/BlUQGOmFBaP8mXJQXtDNFm/QJflhImcyNflhFa6xt8WU5uzeEriDrrO3xZSZhsZXxZxdC21XxZTVQBDk2QIhkwpxcn+TKnZ67M6Zkrc3rmyqICHE7PXFlS0M7pmStzeubKnJ65MqdnrszpmStzeubKKrWVbeXLnJ4/T7CEj/ASTcRaKG3Bv0KUIhJEGv4miQy0deFfb+J+wykILVEoxYkGuBMgYgAsMQJtU8Q03EvjWgSuEcDeB+cwYKqIfihNQEuE2A8Yw0AtAjTGiDlcYolBoDwHdGfxiDEoTWFOWPhL4N8/SuXGYHM8ewk/lFy52hrCg8cPAoUk4LIwbhDGQTRCxC087iaoTUMrujsL/KVz8ozhX2FKYw6uxs8k1gNLdEJ9Au6g1iDWwlIZOToJXlIWjzILd0NYXkG7+6FvCrfMAlYYa42F9mnctoUYAJ6QdqK4XxzrtQ33j2CMCDEDYyIth/GZ5TkScFncnsY2jQIvgvXycqD7GeAiCj3ToIUuLE0USxLNyRGEvxnowXHIyRPEY7C8raNAEVENAh6iNQe1/VDKYDug3/eagHIM85TCukDyot8Pm+I1xVHNYJm4MeNYohDmNI5HSWM7DWCrTEJLEP9+VQrLyOIrZ4solonTRRp7RRqoBnl/RRZL8u3CKDNAJ4b1k+S5jEPLDB6Vo5nGmspzgEZMYlmE3zfjdMvxHsNegzxhmvdcxBX6LS/0G2kZXItjWwt+zemMG4WzY5yXK4F1O4Ex8xwXSoS0dgD346S+BeoNeO4WWrMaU5vBFOawHmb5WVqob8H74rwnI/k5u6SwNwg+GsG2Rp6bzEnD8TjF46ShdhtPPQNScBbal7NSEPsImgEzS+QSIk8IOAni8UP8+A04ukxhW6E7V8ardVdIPc57juD5q4GKDyLH1T09g8cMY09Eo9ySs0F+Zl4ZJ6d4v07msJHnchaPA34E+87/n3grL0bcP5uIOwichAg3nmU1/H2W6MNekcCcZQBQvFpHNAKEsW5Rz5krvKeB97lGKM9hH5rCXoRsMwet6FccOR0LVDmaMcwD4mASc8vFOY7WSj6axn6exLJzWhD6IavuxGNwkWYOa5rTTCZnbQFbiAshPnajWe7BOkB4Sd4rCuN0Eus1zscHjkqErwf5mBzBESWKJeS4m8B8CFZebrEM34Pzn9QVLZM5GTzXFQm4rBDGOs3w2Yebn9y4ntw4yyXgouh+/tcgp6+is/28pFE802J4TnEz/0rdoz5cZnEDfs0SD16ZOsfDH6vbwvnBZXeWz88ZbLnQkjy5XIJ8VlzOV1uBDyBJOFm41YIQK1O5lUcY5944jiPBq0rK+V5wiVdx8SDBnzmpuPIsni9cfArjPBblYwtHB2HGcPS/uo9yUTzOWyZPXZgh0YJVxTSOd1Fezyiqq3C8jPAyCCsMQctLvdqDLRPE5TAhrK+Wx7nlM8G9LC5EcJzej1cUUWx9ZNUgtCENTQGGcK+Rp7lnWeys4WdvPlrkVwMCN+8lO11nNmBLltEYFGiwzpw3o19b5ewkeA23OonxWSTv3dfKcIJXXj3LIcttzc2cdMFahLM35wURfiwuYsd5u3uwzCk++wjrCm5dNMXbWfBjzq+S/HqHGyGB191BLKfgKUEin+WXx7P/BFvkNBTEsiO9RflYH+bnaohfa8cxr4U5M4pX42nsmzyPV7ctlEeX5nmwdk2BjsIFO4TC+XDd9Ij8rkbAXjm6eZZFN0H3y3vH8K4gukxuga/8Giw/a/KZSLChhxB2Z2gXJtQjBR6SxPuvGPa36YIMy3E9gXmJ8JlqNmfLwljC2bCRt3gaz5JYjgdhXi/1pevXamGG56QszDRLfTqvif1YjzN/pB2FbDCLd5ecZiIFHITxGY2Z18vNgBEqyB2Za8RjLvKHsQRCxlu3JIpzq7F9uLzSqjuOc4SQZQr3Z0KeWCmmLO2VxrGCs9UEL/fKOTd4FYumctKnsZfGMXVuFl258/1jPUDIb/1ED747TPRCbTtkyxHcMgBtLETREbgzDrVuaO2GlmrAGOXvV2NLbcd5qB/wtuEcx9EYgfMQ1HfiGNdLsLiOapsBfwhoob49xA48Rg9QG8WYI5j2FmgdhGsPj4d6dEHLNqijch+Ogtx4Q9CL20MM8DmR43QM2tmchEu5GsAjCpxtgdoI0O/n7waA9gCmh/hH4/fi8lCOz16e0wDWEaKMaHYBR4O4hlq3wXUr4I3i8QNYZo7bISxDL9znZOnBHKCRG3hZOTykn3H+DrIR4m8QIC9VAOugH3OT118XXLcC54h+H9wdwxliGHp2Y0lHsfZ6eJ0haQdxLS8VZ6kuLA3SKtJBN5S3wF9fTncj+MzxMlJAbanutuP7eSxOvgB/7sKaG8Y1zhpduDaGbYXuenhbjmA5lo+6HXtiD8YKYIlHcx7Si72X417wTm6M4QJOuPGQbQt5EbyavcYc4agI97fxlr5SL0jrAawTxNdobuSrUYa5+XnW521ay26JhlKJdGIyw3YlUslEKpiJJuINbCAWY0eiU9OZNDsSSUdS+yLhBlV/ZCIV2c8OJyPxsblkhB0MziVmM2wsMRUNsaFEci6FerCIstfPutBljYcdCcaS02x/MB5KhG6B1k2J6TjbPxtOo3HGpqNpNlZIZzKRYjujE7FoKBhj+REBJwGDsunEbCoUYRG7+4OpCDsbD0dSbGY6wm4ZGGMHo6FIPB1pY9ORCBuZmYiEw5EwG+Na2XAkHUpFk0g8PEY4kglGY+mGrmAsOpGKojGC7EwCCMI4wXgaqKSik+xkcCYam2P3RzPTbHp2IhOLsKkEjBuNTwFTgJqJzEDPeBgUkIpHUukGdiDDTkaCmdlUJM2mIiBFNANjhNIeNj0TBL2Ggkkooy4zs7FMNAkk47MzkRRgpiMZTCDNJlMJsAbiFqjHYon97DQol43OJIOhDBuNsxmka+AMuoCMcRgrMclORKcwYW6gTORABjpHb4k0sLyY1Wl2JhifY0OzYFKOb6S+OCg5FQRZUtE00mgkOMPOJtEwQHEKWtLR2wA9kwCB9iGRgiwYYIYbCzlPaDqYAsYiqYaRyNRsLJjK+dU6Yeh1yB9axkFFyASrG3z+JarPpILhyEwwdQuSA5s055lToPEkag4lQPx4NJJuGJwNuYPpGrAi25dKJDLTmUwyva6xMZwIpRtmhJ4N0KExM5dMTKWCyem5xuAE+BlCBczYbCiYnkzEQeGAlR8sPZtMxqLgOOheA7szMQsam2NnwYUyyFlRM1JECEybiXjYcDSdBAfmDJpMReFuCFAicA2CGSOpmWgmA+Qm5rBUgjuCqsBvEimhMIlG8FwpO/hBeDaU8SB33Ad9PaiPMADYZ/90NDRdwNl+GDQaD8Vmwffz3Cfi4CnuaA03LQrQgcK1uOVmEfg62D2dSUVDnEMKA2A/FGi1YQ24ozAKzAkUSlJo5oQT++OxRDC8VHtBTlXgWSAOmA8VZjNJiALhCBIT4UxHYsmlGoW4BL7LoSODRPE8mY5ORDMoPqnGgOXJBJotiGVe1R52IpgGXhPxXKQQjODmfSESb9gfvSWajISjwYZEaqoR1RoBcw8fU2rAvNgt8BxAZFYOgisFr+/yGIMI43tIzTcnQCakGphLMQhsWN1LwyRS5ZJAqVJtRcZJ48kDcoMKItALHBs0E/awkykIemiKwEScApmRjkFXYFHoziYmINjFkVKCOFALfnb9UiCGgul0IhQNIv+AeQYhK54JcvE0GgPNuBHFJdKyo3yk/l4N5iiMoyFnhxXxcJxFzQXu5uHdDXEv3I5FwU+5sRGtFJepYAQ8iZCEHhTLo5PoGsEKSc6CQOlpPGGB9MQsmrxp1Mh7CUjYCIKnIyhEJ5JRLqJelVVuwsOQ3KThNY2Z2D+dmLmGjGgazKbiwEwEEwgnIIZiXm6OhDKCg+X9GJw/HMUTbx3n4hDG9kUKEm48kUFThgvmUX4ac57C30pPo3wwEVkyc4MFgqbQ8OkMOFMUTJTLPNdSAJpv/T3s6HDv2PbASA87MMpuHRkeH+ju6WarA6NQr/aw2wfG+oe3jbGAMRIYGtvJDveygaGd7OaBoW4P27Nj60jP6Cg7PMIObNk6ONADbQNDXYPbugeG+thO6Dc0DHl9AGYiEB0bZtGAPKmBnlFEbEvPSFc/VAOdA4MDYzs9bO/A2BCi2QtEA+zWwMjYQNe2wcAIu3XbyNbh0R4YvhvIDg0M9Y7AKD1beobGIOUOQRvbMw4VdrQ/MDiIhwpsA+5HMH9dw1t3jgz09Y+x/cOD3T3Q2NkDnAU6B3u4oUCorsHAwBYP2x3YEujrwb2GgcoIRuO5297fg5tgvAD86xobGB5CYnQND42NQNUDUo6M5bpuHxjt8bCBkYFRpJDekWEgj9QJPYYxEeg31MNRQapml1gEUFB922hPnpfunsAg0BpFnQuRG1TF1wLF1wLvQbfF1wL/ea8F5Piv+Grgz/PVAGe94uuB4uuB4uuB4uuB5dG8+Ipg6SsCQTvF1wTF1wTF1wR/cq8JYG5y3zUgiMtW4gix0kHxn8gnSDdcx4ilv51z5aGjH1YqScAhb79efJUK43/7evE1GoRPVV4vvlaL8Q9cL75Oh/HPXC++wQD4cCXQNxREGF8EfxpCB+cSUHMjYSc2QCDrJpqxkTaDYbYTu4mbIKhOQyidIw6RduIj5FHiUXoT8ThQegp6PruM5sI1aA4AzXGgGQKaaHF7B9C8D2g+DDQ/CzSfAEromyIvLqVJHimgqQaaJUCzFmiuBZrDQPNGoHkL0JwDmvfA+SGg+Wmg+STQfA4onYWe319Kk3pfAU0N0FwFNOuBZjvQ3AY0w0DzDqB5FGh+Amj+PdD8MtD8BtD8V6D0c+j55lKacCdPUws0WaDpBZodQHM30NwHNB8Amo8BzeNA8wzQ/AXQvEBvIsX0w6QZZC1dSlMULaCpA5rlQNMPNNFECgLNg0DzE0DzH4DmV4Hmfwea/xNoXgKaCqDpBJrVaH5IxaSUOXf//W/de++9b0lFpFTy1vw8/Jt/S0qSUtE8f6A7Yr78llRKSuWnT38WjkcekUpIqXRx8TOfefDBo0dx5cBhfBxApCWYLk9Asvf++Q5We/9ejHZYQJMQUsnh/n6vt7//MGYHSECvew9IaFIiOseNn2eGmKdpYObYsWN/FO8yUqp4Yf6F+U8BPAhwL8BSGRhSKlvbfQiO7rV4iOuQgSGkzKFut1br7j4kE5MykEEQQkRKxE8soMFlJCkTuMJSyJAUMgkpk6IhLgClC7jzhXlOjguFPaA/3JMIlQsyOSlTLsDxWMdjHX+N4SiATErK5C889tgDH/jA3XffhWvtnXeio7MdD4WHEcgxyXvn55NS6b1JGUPKZIe4o3utTErIpHd2VlZaKys775RLSLlUJBJljkLfoxlGRDK8SPNykpKLczLNi0SkXHI/HHKGlMvwUIeB4EVM4SJiGyFelJOkPC/XPLrL5GoX5QpSrlrYu7AXtHPsAfYB9j6AwwByKSnHsnHCyWWkXLEBYtJ8wRGAmYBHQ4NzgsrFQB4JuleLJMVU7uSPzna5lJBzomJZFRIS/Vz7isIqSEohCMtLq8DSKhhSIeMGxOJiIhfnc/IqSFJRIO88up8XGO6rSIVmwbpgPeY+5r6///5+5Dp3S++WHpIqZKRCsTB/DOB+gHvnDwMcArhzHt8qgbhZqIEA1EsIniHghVMBZujA4fn5Di8Id/gA7jp/xYGUp5DBP1QsBzBCxDHiEhpDyZBKGQXHul7kJr3r8IzglTOvJCllzj159SgZpB6llFTKL7744ouLF188ffr0ixcxoSxy3ovotJBVUtB3oeBAGNKCelapJpXacyXnSt5q/7bn1dirsZcGz5xZPPr1o6eVp5VKOalUnlt4a+HbC68CnAF4EeCfF04vvLCgVJBKVSlxK3gUcioB9i7culBK8KxhrnIDy9onFxbOHShRSyRnDmDaCyscwfmNXPfTpycn263W9snJ06dVUlIlp+FomzqNjqk2PM1ePcd3UlGUqkBQYmFBLCFV0jPoKMjXaL1ChWPxKb7ckObK46gcSAUnPGwgNRP3sF1zqZiH7YskbsHnFJxTESijt2MedjCYib83bMwDifmAP+cn4WrkWHI+7D3k/KhEVnuk/8hvVSRDHTvkPAxN8xRJNim8Mom4Tk1TdjHhDUrkdRJSRB5aQ5GiY6PeG7yegpaST62aL4GEimAY7+MS+MkK2vdvQOAtKyAmMn6avuML/zr21PjvS5//WNuXHg/dMF55x7FD1m3eQ6LT3kP0F47RFElRBj9aIRyYX03O2qMpzPCL3v9bzFWHRbV1b2YYOmUo6e44M7QISHd3S3dIgwUD0khcGmkBEWkVlC5BQEVARJAG6RAMFJDfDCjyef2+e39/3OfC88Cz9p6z9z57v+t99zp7nSE4GS0IAzku/6NhoutDMKFgfV0YFDiDMrChuIZW3o5O7g4+Hu4wYoAQVYgFxdKxs3XzcLeF0QE0qBJcKNlvU1JgjAA9qh4dSvmzXs/JzY5X18fKzZNBS1YaoKMggAkDYoAITERIVEjABGmKnjKBkNp/ZGQEAB6qHg8KUdfU0oGxA6zHJp27rJMn6qhaTleeQV5X45yCEFyUV0BERIRXVFpEGMYKMB/fEc1v70j3+MAfQICYTs8wCAMNHQEiQkOW44IRyF1lOR4z9Z3eSA5S4bkOR3PMMA5f6QiSO7dKBcEX88sVHuIS3CsaIlCQX6rModnxtjj02H+YzpvyiZo58pN27WKWocGBel+B0KMFqz4HUjCF3G4UmWIeL248WmVfRKuK7VPR5plY7pWOcIGH3K1UVV/YMzEBT9GpRmhn8AuVi+mX5mY6POoSzinOEuOVeUWaXWORJRy5W8IoGDl2zz9hYYboyh8U4cxxZ4e6Lz0p+lSlxZNr0m9SBepORnSC9sjAdmvuzRRovBEYidEWcSKxOLnN9tPubq+m81TGJ5Nzgq6+IbdvBXHxa7J/NVnYfU+7Sgj55CJPR3q11TZ1fODRocJz5xZvejA60o8KESAc5IxgALTIKaUlhJBDSIdbPsGrImFE784mv5dsgX01BRPhHGGIlhlCCZAHkzIL7r7RUfDEXb+w57dXy13VIVRLBOihPkAPUQdUAeU8xTz5cNnvOQI2Xq6/JJZ4ujihSvm/p2h4858sI2oVjxYRiUo+5EcAI0xspGNiYGCBQBA1QAVQ+mED4PDz3zvw9/f/XQd2Xv+jZR8AihovKwQfwP3RJDr2Lw6JjkJJuina281CpZh5LTGHZJZWj/jmC1NixTzqUTx3jCXhuM79+2YUkHRAc/AQv+DGJGs75Bz2Z415UO2ku6ydxrQEn7wnp++gppMmeUDt88uSm2fvqVdX+MJ1WDDSEkaVxpbk9hKsyI0tnlVz66fk6pi1tQLsWBsjauyBtR2fVYQIzqoXwrreDlExxbHjCF4QeZ6jRBPtGy2bPcqpd/+OiCtpTk+Aa93ZuxEBhSK2zaCktYkL1y3PEOslY5iMXa/lUCXJEUTE8HNcFCF+70A1jPAen4LvTQkUzl0QYmwUMYU7evSNci+BrGwS0yLfrWxVgSu/fDbbnwrpELx2X3uCmn5NZ+0rgMAEIWls+RSNdS5H7QaFaC0fHtFY5+lZw0PS2LV/hCw4ALZjp6c/XW9rx6Dr5HCUoIFcWFRmHuyIzUQAURgMDiB/BY/Z7KcJ+Pwj4/tej/5f6v+SjSKj61k6sOIzgwPJ9tku7ntF8nz9UJgWmapQV9hnGcV/ToCPLjHg65VSegToQVAfVSN6r8JqV8bnPQjt9g3cQyb3/G0HiS52ygUO+o+QZGmbtbnHZLHr0EyhSVFPPQ/xtXJ5HEC5rTkeyMDv83v62TuF3P9lTENyN/YNhnW6O0LvL7VP+6CpRg++TVwdCfgW97X8YqRE0yP6Cuu0lq6w6oSKkUruIb09obFnl5Le0R2uXXLpu47t5zNNrK00/B6tR0mtEEtowZjg4Mqtnncmczc+jmQS0d8sng+jaBvpzaUFdR8olUCTBNIYleC77SwFaDXNur2h7pymIZui7sE7DWtQvNUfbBSMnJErx3TDiqKbE2VWwwadeCr6KbrqG7EOe3FRbOXQod1ssKehrK4Dmg7ooKrPQJBcdFsRkP9VaQQBOMrEgHLDBQAABue2EQUErYXsrHgFxawFeQXhAqK8ogLCcF5bUSGYvRUcLiRob/MfFKjkbrughTGEuEshIsL0wO1Ory845b9T4G8ZysPT+4gFkXBB4hiJYiSAUfi1RP3hBUR4AdEjCrQ6RYH6AHK3cooC5f+ygx8s+D+68AHwUQOHgkCHEDCA9os7oyPAIDRMcvpxw3atHmbNAu2A1+u7B8+aXrW+/0JtsK7b46SI8aqzb212P8M0xfKMKEcrhjx0OjMwstG+bLxhFazPXCfBHCDtVrH7Hs0kOSOaph8nZSCTRg4oLSLvfqxo+pFbMCY33kikQ4OmkqmX+NkogrhUaKuCqSeepTgkZoqdZt6eNkqS79AQXb3NPTQPvnq/ll/LwByzmiy2h9amzht/biSIjYgrVb4EHiqZKmmo7M8c9a2auDt6AZtMu4vbBGYq5px653akSyqHx/vOipUmeYp+a42QB3pUijfTi9xa3dmf7LLT96wzlOJVv3+Ol5k865ztFJov/NqN4duNV4cd9WnCON8kSNvSSUtbw/s3EW1l+iyylA+UbgSED3wZzJY6+4Y0ajEu15El0lG8tDtYg20Rm1HN5uDWH2TqAg8MLmq+VnkkevOQb6La8rasy9OAF9UNLvGhrhFed1eK9nInqEbE9m2fukliL1wJrS5vLHx8+UWqwe0goz4SRetBxs39850wvM/8krZFIh4XtaTq5BI08/Bimq8Zfep2iLAaz0nv7Int81CcaeVLXq/+VAW4rTkr31lO9etpwu78Jv6xwlsEs8bgxdnhho/JvRE028HOIM2H1CHetUOmTFLnjCinIjccOpVL+N+yxkhYDKwJyiXSNibi+yEkNztHefMh4JtKXzYnwC/QC5AigIUUgc1jEcC1IncUPOJ+ml+3sJZHdIqLk8QW9cc2jy3oLDk6Eo2wswDFfxTinIAVCUPuY95k+cmbOh4eSPJEQtfJ3snGyseOQdrXx9HDy8knEEXugAggCAjA4EICgBiS3OGwI1MAQJn/3h76r/g9N9+1empcKYnrigvf2Zmm2bmuDG1mrfLnE5QaLEQbL0teqpX7AAxnVrFe6aWQKSdTyyRVpJsBbGNoLkuXm9aisIg+E0LSt6L66fsEWCKytz840PDsX16MpF1Z1CjMb2PW7Y37Kv8CZ8CicqBKBlLwpdj1D4fXHG8VdKvCBxY4FPjY74Vr6uvgz6Pz7DknJADuETvGQPbXayNptUuMadd2B6E72HW6bjr35RNyldBUFO3PsHPa30mbH8IMUSn4ElZyRpEUB5Ebtq4f8A2USauFfQONGFBYr5tkVmjo5NXLraQLkIb592dNiYf+kW8FfkBLUL3/OasG9JxJVe/wC0ZHOwPeD34vQ85ICUB0wjgYADry3yk+/+3uEkXftEQQCBJ/4QAxJs53TSADoUrQgJD0Y24OSQBC4oJJCe8hLl4wYE9bYIXuc83g6qYYz9/Ot7lt9Y/DE0EcWE6er5JXVK7mbfQBC8pnB2gdi4IygNShPNk86XCpv78vPqlGZWqjqPxIEPROCYISoADInRIE0f/Pnhh1H7LHrf7N/TByronTojvM0OWEJ5bvl/uPPw/UVgdV8/lcMnXDh5Y9b74cX883TFIQ62Zdbwju02CAamVMBF2YNWyoNMqkmaEFhd9rCNiOGVgTB23MNsfjYvTEKc1u6ZJNaJYlzS/GOb8KbnuXvI3JfwN9OZGLhclz79P+fEAGH8FnrFnPRkqN7JsuuF4p9flitxx4u7QJV6zNpMjTYxikZrGo4F/6YSp+MAluL7yeFU+Jwxu40Kl2XKubW6/rKVY1Yq53CXFbFLasNl7Fk7k8rOvFuAH0NgTYmZmCKHBJCQfHSNM/nn9kb1TLy7/45UZ4v7bBUrZnsus9MbXhT4EtdymDrDk3C7I4BTH9qayfStC50SO28Lp5Gl7I1i58Wbv6YO72HR+heo2uS8wkbH5453ViL5koyJI21tZWqTv05MocBgcyBueQAfZLMiQWVD05TIwDssvcyw0flPp5hkfhwWpsXEosliYrBpvFkxnZvec8mkLYfTDPbPgxtmQh2tj1HlY7S0Tl+1ndd8+HFrfcVdwi8TiIhrvWfJvS7ollfmrflE0bQWILluCtNI6vn2dceFDVa3M/QA9jWJpP615yVVFAWW1eqi/Vm6QIqC8TP/wOtnueaSxrS95mWC/jyCqd5tPMDeXpzyA7jyi8qz1OPe/cV0rSnsM4Dwm7TM1G1anzR7/y50jx6ZO7PIUWHgAIrCAAgWH9QwoIEwaPpAD91zAgJPIfoWI4ABw7JOffccifEQEMKRuicEBI7Fg0hI9MGIAy//WIBQH+s3aAUdoBRmoH0ufKtr56EdPwlY+630UQqws+3n5oxJgrQ83lsmyidbceU5QKovz4egc+3YSIyxOSUbwt0fYMzKoesVcgUpjMUBRBoG3EteSLLK6VOcq3lh0tBqeydGtweToq35RyVwThVL5ONe69SIWxbO+3BNdhI+FfLMPWelErV2c+2smH7lvmuNPntnPOLJ/8g8LjaVHbe+62QgHFeTZEvEMX/tidm8QieGUWWKTMuUjQnAf1b06W2Nyb4zYhplc34CgI8pomOVenbDG6vi6bGPrmcs3lcOo3ktWx5ktRmmFU2/n8xvMJ4rwVAkZddZLf4EO16BLVNZVJotcGs4N5PmoYJDIKsXaIudte1318i6j8LHNY34fH6OFxny23BnRaYpMjGlsZfVgtKTke9rNziLKmi6kIv7hSnVRBw1xSar9mRe88w6GcbRk5y2o+xKgqqdP5wFCKBX3rZZAp/yvmOU9zIm0F/9pdtJnGe2CE5XgrWW0T9bC+6qJYPtEys3IjZb3cFfn5tg6voGmvRZapFoWMrs12GsPx0Lg1dWWgpOzm1JppbuX+RJX9bFtayOX1kXXVRWXOEihHcclVh+B30dYBljX8Ya8Nb5m1+HNwvF936+CI54m/IKLZNnNDLqoTR61ruEiW3yfls/tuAIMRD9T8YkqmpKZA2FhVJMVkjsaH1KpGhTzX9MHpkcjYE+1cR2rn8m/k76d4/jYuOXtyASkYgk+Hi6Z7lKAiiyb9n7r6J1E+HfF48Z4DwxJkH5FiaMyslHTDXjJHCQImx+KGeoSqmaeepxqu/P966IP0W6TXIp31JCixBAQs4fAjmbM4JXM6gBagcUrmZP6ezP2P9n2AkFzU4BkgIWlASDIQkngySXzoQEgoIPWjOzCIXOCvwizU21PIO3Nys/IKtPH05nP0cQMunDQABgTp4Ay0aGpoqC9sQuUCWR7lAh3njgUiLe/vWW12J7l9fAy0vwvEHLbDi9Kn9QKp+IZGfRyYsvBSz8zYJGXIpF4dDMRPaLOz5OOR3O3weukW+q1Zagm3V7xFsbRwx2ncpoVJqCjN3C4s4WqMgpb+KH7SlUEqVZqd8zIxOgNVBy5zklh8nFnvJKiLhh/Q+ieLzS7bPpWTCAhi3oFeLU7wCY370McGVuBqjyZuuF2KgZ+17vjVkS8lj0uKy8VI2YYex8ndJD11PvRDa/yOAvfkvvhAk9CmO2vFQiX7+sDEDmFlBkdaujqhBN42dtQIfQeccnari/e5ac59ZTHcJ7jtT8orFmrejJNFassbicIvsVNdr/7AvjvJc47BKb3GOMrR3aOkzqfjAgZmMYiLQxIhBVW3x2utVf84E3+dxoPsqnyJ38IFLrvCDnMd6/AOWhvhtPCpsZ3dbfL8TPaZZ0VpAxvmNtJzpli3IiQx/TFfYlb70pM2W1k92Hr7hBrSPCXdTcixMWnHv5b2Kd8sdRRtJF+hyXgnrQhHVYk4I5h+AI2zqzqrSEren07oyWBBQW5QENNXpRT6sj1F5uCPObstLnWqabOrvgFUaysiGYGUqocjtcyOvu8qv+7HrOIFrziJV+4D6xC1m1NTvm42iRIvsw00NFuCDZnyA87AGYM2pXGrpfbu9N82b8uPzDK8ZKChJN8q8zTLzxQ3WMnlIDC3rcnNzfmpjjeUIEjrGQwBqQIQkHtgEAgISfm3hev3jwN/Ho7khXSiyOc7iHHQYfinT16Qo/hp4cEIgdO1ZADzzwshMCS1HSTLldzcfj8SQjLF2eSWEPZwlWoSsD11CT7MANDL4wrm+O0rB3p//haofLZglv/q2Xonbz8y/KLNEAQITVfxZnHowxwPE3bMcZiFDn9DrTaWFIyQNqjCX1HPrEVEkEiEeEjXnkUfc0wnkWwpPZPcycuUp6J2no+TmJVQAXfPKSJJ0fVJkq3qeHs0ZMpxExb+evJ+b3nielyx9nWPgFIQpPGgse5Rz/L6QVcE2thiQ7Zt4aB4t2u35d7y3mOygTRR13VuzO1NxYgzAQO0h4biz2aN6AyWuiOxSdqLXTNuLey1ctrtnj+Pfk/pPpN0EGNJ4zvS/gTZPVPqdU0/Sum7B6VKRNHi+vXO7Y3F8Akb4mZho5sYfFI0CeYFcYtLVFFLyenPAj9JrtK4IAidQb2NBmyOtwnop9j0RlV5TBmj8xFgDuT2hOXnGmHCEGAyZNGZI2je/NcC8d+ftJ3CpDlAeRqSeD9PDEHIzk9qMGBERw+OhWFCcBjqx+RPiJRdDhPP0eLoXmWLJXMfbnWkzXoY+EvIhMIKTAN6HRxliE5jrJLms4obqsIpQMXZbb4zNre9caUsOYt5Ce5Asoo/O/YqToPVma1wKjPYIoN3UNjCjrT0zVzlNXK3FWmKAZ+JQ49NnHyZnG2VS9e5dExy6DfAtbzKyXKMwxtf8LCsVvUDr2EHXkvzhFrm2ZlyYNDbd9f02GcPb1hNSvsp1h1Mji0cIL4t2Bi/eDxXk0bg1Dl4KeX9Rz+5R9OdgS+/Pb9dj5cLw9BdUKtveESvb56/E7acNBnXWIUXsgrNlhR2drnVby79cvn2q/HC2qWxcfyrUKNRGZ5h94bXnOJhqzIEraFY2jPndsqM1Wqi/UCble2c275F0TCxt3FyaP8HvTIZxw0KZW5kc3RyZWFtDQplbmRvYmoNCjIwIDAgb2JqDQo8PC9UeXBlL01ldGFkYXRhL1N1YnR5cGUvWE1ML0xlbmd0aCAzMDYyPj4NCnN0cmVhbQ0KPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz48eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSIzLjEtNzAxIj4KPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgIHhtbG5zOnBkZj0iaHR0cDovL25zLmFkb2JlLmNvbS9wZGYvMS4zLyI+CjxwZGY6UHJvZHVjZXI+TWljcm9zb2Z0wq4gV29yZCAyMDE5PC9wZGY6UHJvZHVjZXI+PC9yZGY6RGVzY3JpcHRpb24+CjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iPgo8ZGM6Y3JlYXRvcj48cmRmOlNlcT48cmRmOmxpPlNhcmFoIFNhbnRvczwvcmRmOmxpPjwvcmRmOlNlcT48L2RjOmNyZWF0b3I+PC9yZGY6RGVzY3JpcHRpb24+CjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iPgo8eG1wOkNyZWF0b3JUb29sPk1pY3Jvc29mdMKuIFdvcmQgMjAxOTwveG1wOkNyZWF0b3JUb29sPjx4bXA6Q3JlYXRlRGF0ZT4yMDIyLTA3LTIwVDEzOjA1OjM5KzAxOjAwPC94bXA6Q3JlYXRlRGF0ZT48eG1wOk1vZGlmeURhdGU+MjAyMi0wNy0yMFQxMzowNTozOSswMTowMDwveG1wOk1vZGlmeURhdGU+PC9yZGY6RGVzY3JpcHRpb24+CjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyI+Cjx4bXBNTTpEb2N1bWVudElEPnV1aWQ6OTdDRjhCRDktQTRDNy00MEMwLTg4Q0YtNTE3Q0MyRjFENjRDPC94bXBNTTpEb2N1bWVudElEPjx4bXBNTTpJbnN0YW5jZUlEPnV1aWQ6OTdDRjhCRDktQTRDNy00MEMwLTg4Q0YtNTE3Q0MyRjFENjRDPC94bXBNTTpJbnN0YW5jZUlEPjwvcmRmOkRlc2NyaXB0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKPC9yZGY6UkRGPjwveDp4bXBtZXRhPjw/eHBhY2tldCBlbmQ9InciPz4NCmVuZHN0cmVhbQ0KZW5kb2JqDQoyMSAwIG9iag0KPDwvRGlzcGxheURvY1RpdGxlIHRydWU+Pg0KZW5kb2JqDQoyMiAwIG9iag0KPDwvVHlwZS9YUmVmL1NpemUgMjIvV1sgMSA0IDJdIC9Sb290IDEgMCBSL0luZm8gOSAwIFIvSURbPEQ5OEJDRjk3QzdBNEMwNDA4OENGNTE3Q0MyRjFENjRDPjxEOThCQ0Y5N0M3QTRDMDQwODhDRjUxN0NDMkYxRDY0Qz5dIC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDg2Pj4NCnN0cmVhbQ0KeJxjYACC//8ZgaQgAwOIWgah7oEpxjdgiuknmGJeAKZY+iHUEQgFlGMCa2eCUMwQigVCsUIoRggFVckG1Md6C6ydPQ1McbCDqcxNYKr0NwMDAFjEDQUNCmVuZHN0cmVhbQ0KZW5kb2JqDQp4cmVmDQowIDIzDQowMDAwMDAwMDEwIDY1NTM1IGYNCjAwMDAwMDAwMTcgMDAwMDAgbg0KMDAwMDAwMDE2NiAwMDAwMCBuDQowMDAwMDAwMjIyIDAwMDAwIG4NCjAwMDAwMDA0OTIgMDAwMDAgbg0KMDAwMDAwMDc2MSAwMDAwMCBuDQowMDAwMDAwOTI4IDAwMDAwIG4NCjAwMDAwMDExNjcgMDAwMDAgbg0KMDAwMDAwMTIyMCAwMDAwMCBuDQowMDAwMDAxMjczIDAwMDAwIG4NCjAwMDAwMDAwMTEgNjU1MzUgZg0KMDAwMDAwMDAxMiA2NTUzNSBmDQowMDAwMDAwMDEzIDY1NTM1IGYNCjAwMDAwMDAwMTQgNjU1MzUgZg0KMDAwMDAwMDAxNSA2NTUzNSBmDQowMDAwMDAwMDE2IDY1NTM1IGYNCjAwMDAwMDAwMTcgNjU1MzUgZg0KMDAwMDAwMDAwMCA2NTUzNSBmDQowMDAwMDAxODk0IDAwMDAwIG4NCjAwMDAwMDIwNTUgMDAwMDAgbg0KMDAwMDAyNzA1OCAwMDAwMCBuDQowMDAwMDMwMjAzIDAwMDAwIG4NCjAwMDAwMzAyNDggMDAwMDAgbg0KdHJhaWxlcg0KPDwvU2l6ZSAyMy9Sb290IDEgMCBSL0luZm8gOSAwIFIvSURbPEQ5OEJDRjk3QzdBNEMwNDA4OENGNTE3Q0MyRjFENjRDPjxEOThCQ0Y5N0M3QTRDMDQwODhDRjUxN0NDMkYxRDY0Qz5dID4+DQpzdGFydHhyZWYNCjMwNTMzDQolJUVPRg0KeHJlZg0KMCAwDQp0cmFpbGVyDQo8PC9TaXplIDIzL1Jvb3QgMSAwIFIvSW5mbyA5IDAgUi9JRFs8RDk4QkNGOTdDN0E0QzA0MDg4Q0Y1MTdDQzJGMUQ2NEM+PEQ5OEJDRjk3QzdBNEMwNDA4OENGNTE3Q0MyRjFENjRDPl0gL1ByZXYgMzA1MzMvWFJlZlN0bSAzMDI0OD4+DQpzdGFydHhyZWYNCjMxMTQ5DQolJUVPRg=="
        },
        "validUntil": "2022-07-20T11:56:28.269Z",
        "data": "",
        "documentPurpose": "",
        "documentType" : ""
      }
    ]
  }

  submit() {
    console.log('Cliente recebido ', this.client);
    this.updateData(true, 1);
    this.newSubmission.merchant.commercialName = this.form.get("franchiseName").value;
    this.newSubmission.merchant.billingEmail = this.client.billingEmail;
    //this.newSubmission.merchant.businessGroup = this.client.businessGroup;
    this.newSubmission.merchant.bankInformation = this.client.bankInformation;
    this.newSubmission.merchant.byLaws = this.client.byLaws;
    this.newSubmission.merchant.clientId = this.client.clientId;
    this.newSubmission.merchant.companyName = this.client.companyName;
    this.newSubmission.merchant.contacts = this.client.contacts;
    this.newSubmission.merchant.crc = this.client.crc;
    this.newSubmission.merchant.documentationDeliveryMethod = this.form.get("preferenceDocuments").value;
    this.newSubmission.merchant.establishmentDate = this.client.establishmentDate;
    this.newSubmission.merchant.fiscalId = this.client.fiscalId;
    this.newSubmission.merchant.foreignFiscalInformation = this.client.foreignFiscalInformation;
    this.newSubmission.merchant.headquartersAddress = this.client.headquartersAddress;
    this.newSubmission.merchant.id = this.client.id;
    this.newSubmission.merchant.knowYourSales.estimatedAnualRevenue = this.form.get("expectableAnualInvoicing").value;
    this.newSubmission.merchant.knowYourSales.averageTransactions = this.form.get("transactionsAverage").value;
    this.newSubmission.merchant.knowYourSales.servicesOrProductsSold = [];
    this.newSubmission.merchant.knowYourSales.servicesOrProductsDestinations = this.lstPaisPreenchido; //tenho de mandar apenas o CODE
    this.newSubmission.merchant.legalName = this.client.legalName;
    this.newSubmission.merchant.legalNature = this.client.legalNature;
    this.newSubmission.merchant.legalNature2 = this.client.legalNature2;
    this.newSubmission.merchant.mainEconomicActivity = this.client.mainEconomicActivity;
    this.newSubmission.merchant.mainOfficeAddress = this.client.mainOfficeAddress;
    //this.newSubmission.merchant.merchantType = this.client.merchantType;
    this.newSubmission.merchant.otherEconomicActivities = this.client.otherEconomicActivities;
    this.newSubmission.merchant.shareCapital = this.client.shareCapital;
    this.newSubmission.merchant.shortName = this.client.shortName;
    

    console.log('Submissao ', this.newSubmission);

    this.submissionService.InsertSubmission(this.newSubmission).subscribe(result => {
      console.log('Resultado obtido ', result);
    });

    
   

    //this.route.navigate(['stakeholders/']);
  }

  b64toBlob(b64Data: any, contentType: string, sliceSize: number) {
    const byteCharacters = atob(b64Data);
    const byteArrays = [];

    for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
      const slice = byteCharacters.slice(offset, offset + sliceSize);

      const byteNumbers = new Array(slice.length);
      for (let i = 0; i < slice.length; i++) {
        byteNumbers[i] = slice.charCodeAt(i);
      }

      const byteArray = new Uint8Array(byteNumbers);
      byteArrays.push(byteArray);
    }

    const blob = new Blob(byteArrays, { type: contentType });
    const blobUrl = window.URL.createObjectURL(blob);
    window.open(blobUrl, '_blank',
      `margin: auto;
      width: 50%;
      padding: 10px;
      text-align: center;
      border: 3px solid green;` );
  }

  setAssociatedWith(value: boolean) {
    this.associatedWithGroupOrFranchise = value;
  }

  onCountryChange(event) {
    var index = this.contPais.findIndex(elem => {
      if (elem.description == event.target.id.description) {
        return true;
      }
      return false;
    });
    if (index > -1) {
      this.contPais.splice(index, 1);
    } else {
      this.contPais.push(event.target.id);
    }

    //var index1 = this.lstCountry.findIndex(elem => {
    //  if (elem.description == event.target.id.description) {
    //    return true;
    //  }
    //  return false;
    //});
    //if (index1 > -1) {
    //  this.lstCountry.splice(index1, 1);
    //} else {
    //  this.lstCountry.push(event.target.id);
    //}

    //var index2 = this.lstCountry1.findIndex(elem => {
    //  if (elem.description == event.target.id.description) {
    //    return true;
    //  }
    //  return false;
    //});
    //if (index2 > -1) {
    //  this.lstCountry1.splice(index2, 1);
    //} else {
    //  this.lstCountry1.push(event.target.id);
    //}

    //var index3 = this.lstCountry2.findIndex(elem => {
    //  if (elem.description == event.target.id.description) {
    //    return true;
    //  }
    //  return false;
    //});
    //if (index3 > -1) {
    //  this.lstCountry2.splice(index3, 1);
    //} else {
    //  this.lstCountry2.push(event.target.id);
    //}

  }

  countryExists(item) {
    var index = this.contPais.findIndex(elem => {
      if (elem.description == item.description) {
        return true;
      }
      return false;
    });

    if (index > -1) {
      return true;
    }
      return false;
    
  }

  countrys(continente: string) {
    this.valueInput();
    var count = 0;
    switch (continente) {
      case 'EUROPA':
        if (this.inputEuropa == false) {
          this.inputEuropa = true;
          this.countryList.forEach(country => {
            if (country.continent == "Europa") {
              if (count <= 19) {
                this.lstCountry.push(country)
              } else {
                if (count <= 39) {
                  this.lstCountry1.push(country);
                } else {
                  this.lstCountry2.push(country);
                }
              }
              this.contPais.push(country);
              count++;
            }
          });

          //this.lstCountry = ['Albânia', 'Alemanha', 'Andorra', 'Áustria', 'Bélgica', 'Bielorrússia', 'Bósnia e Herzegovina', 'Bulgária', 'Chipre', 'Cosovo', 'Croácia', 'Dinamarca', 'Eslováquia', 'Eslovénia', 'Espanha', 'Estónia', 'Finlândia', 'França', 'Grécia', 'Hungria'];
          //for (var i = 0; i <= this.lstCountry.length; i++) {
          //  this.contPais[this.lstCountry[i]] = true;
          //}
          //this.lstCountry1 = ['Irlanda', 'Islândia', 'Itália', 'Letónia', 'Listenstaine', 'Lituânia', 'Luxemburgo', 'Macedónia do Norte', 'Malta', 'Moldávia', 'Mónaco', 'Montenegro', 'Noruega', 'Países Baixos', 'Polónia', 'Portugal', 'Reino Unido', 'República Checa', 'Roménia', 'Rússia']
          //for (var i = 0; i <= this.lstCountry1.length; i++) {
          //  this.contPais[this.lstCountry1[i]] = true;
          //}
          //this.lstCountry2 = ['São Marinho', 'Sérvia', 'Suécia', 'Suíça', 'Ucrânia', 'Vaticano'];
          //for (var i = 0; i <= this.lstCountry2.length; i++) {
          //  this.contPais[this.lstCountry2[i]] = true;
          //}
          this.continenteName = continente;
        } else {
          this.inputEuropa = false;
          //this.lstCountry = []; // só podemos retirar da lista os paises deste continente 
          //this.lstCountry1 = []
          //this.lstCountry2 = [];

          this.countryList.forEach(country => {
            if (country.continent == "Europa") {
              var index = this.lstCountry.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index > -1) {
                this.lstCountry.splice(index, 1);
              }

              //if (this.lstCountry.indexOf(country.description) > -1) {
              //  var index = this.lstCountry.indexOf(country.description);
              //  this.lstCountry.splice(index, 1);
              //}

              var index1 = this.lstCountry1.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index1 > -1) {
                this.lstCountry1.splice(index, 1);
              }

              //if (this.lstCountry1.indexOf(country.description) > -1) {
              //  var index = this.lstCountry1.indexOf(country.description);
              //  this.lstCountry1.splice(index, 1);
              //}

              var index2 = this.lstCountry2.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index2 > -1) {
                this.lstCountry2.splice(index, 1);
              }
              //if (this.lstCountry2.indexOf(country.description) > -1) {
              //  var index = this.lstCountry2.indexOf(country.description);
              //  this.lstCountry2.splice(index, 1);
              //}
            }
          });

          //remover os paises relativos a este continente
          this.countryList.forEach(country => {
            if (country.continent == "Europa") {
              var index = this.contPais.indexOf(country);
              this.contPais.splice(index, 1);
            }
          });
        }
        break;
      case 'AFRICA':
        if (this.inputAfrica == false) {
          this.inputAfrica = true;

          this.countryList.forEach(country => {
            if (country.continent == "Africa") {
              if (count <= 19) {
                this.lstCountry.push(country)
              } else {
                if (count <= 39) {
                  this.lstCountry1.push(country);
                } else {
                  this.lstCountry2.push(country);
                }
              }
              this.contPais.push(country);
              count++;
            }
          });

          //this.lstCountry = ['África do Sul', 'Angola', 'Argélia', 'Benim', 'Botsuana', 'Burquina Faso', 'Burúndi', 'Cabo Verde', 'Camarões', 'Chade', 'Comores', 'Congo-Brazzaville', 'Costa do Marfim', 'Egito', 'Eritreia', 'Essuatíni', 'Etiópia', 'Gabão', 'Gâmbia', 'Gana'];
          //for (var i = 0; i <= this.lstCountry.length; i++) {
          //  this.contPais[this.lstCountry[i]] = true;
          //}

          //this.lstCountry1 = ['Guiné', 'Guiné Equatorial', 'Guiné-Bissau', 'Jibuti', 'Lesoto', 'Libéria', 'Líbia', 'Madagáscar', 'Maláui', 'Mali', 'Marrocos', 'Maurícia', 'Mauritânia', 'Moçambique', 'Namíbia', 'Níger', 'Nigéria', 'Quénia', 'República Centro-Africana', 'República Democrática do Congo'];
          //for (var i = 0; i <= this.lstCountry1.length; i++) {
          //  this.contPais[this.lstCountry1[i]] = true;
          //}

          //this.lstCountry2 = ['Ruanda', 'São Tomé e Príncipe', 'Seicheles', 'Senegal', 'Serra Leoa', 'Somália', 'Sudão', 'Sudão do Sul', 'Tanzânia', 'Togo', 'Tunísia', 'Uganda', 'Zâmbia', 'Zimbábue'];
          //for (var i = 0; i <= this.lstCountry2.length; i++) {
          //  this.contPais[this.lstCountry2[i]] = true;
          //}


          this.continenteName = continente;
        } else {
          this.inputAfrica = false;
          //this.lstCountry = [];
          //this.lstCountry1 = [];
          //this.lstCountry2 = [];

          this.countryList.forEach(country => {
            if (country.continent == "Africa") {
              var index = this.lstCountry.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index > -1) {
                this.lstCountry.splice(index, 1);
              }

              //if (this.lstCountry.indexOf(country.description) > -1) {
              //  var index = this.lstCountry.indexOf(country.description);
              //  this.lstCountry.splice(index, 1);
              //}

              var index1 = this.lstCountry1.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index1 > -1) {
                this.lstCountry1.splice(index, 1);
              }

              //if (this.lstCountry1.indexOf(country.description) > -1) {
              //  var index = this.lstCountry1.indexOf(country.description);
              //  this.lstCountry1.splice(index, 1);
              //}

              var index2 = this.lstCountry2.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index2 > -1) {
                this.lstCountry2.splice(index, 1);
              }
            }
          });

          //remover os paises relativos a este continente
          this.countryList.forEach(country => {
            if (country.continent == "Africa") {
              var index = this.contPais.indexOf(country);
              this.contPais.splice(index, 1);
            }
          });
        }
        break;
      case 'OCEANIA':
        if (this.inputOceania == false) {
          this.inputOceania = true;

          this.countryList.forEach(country => {
            if (country.continent == "Oceania") {
              if (count <= 19) {
                this.lstCountry.push(country)
              } else {
                if (count <= 39) {
                  this.lstCountry1.push(country);
                } else {
                  this.lstCountry2.push(country);
                }
              }
              this.contPais.push(country);
              count++;
            }
          });
          //this.lstCountry = ['Austrália', 'Fiji', 'Ilhas Marechal', 'Micronésia', 'Nauru', 'Nova Zelândia', 'Palau', 'Papua Nova Guiné', 'Quiribáti', 'Salomão', 'Samoa', 'Timor-Leste', 'Tonga', 'Tuvalu', 'Vanuatu'];
          //for (var i = 0; i <= this.lstCountry.length; i++) {
          //  this.contPais[this.lstCountry[i]] = true;
          //}
          //this.lstCountry1 = [];
          //this.lstCountry2 = [];
          this.continenteName = continente;
        } else {
          this.inputOceania = false;
          //this.lstCountry = [];
          //this.lstCountry1 = [];
          //this.lstCountry2 = [];

          this.countryList.forEach(country => {
            if (country.continent == "Oceania") {
              var index = this.lstCountry.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index > -1) {
                this.lstCountry.splice(index, 1);
              }

              //if (this.lstCountry.indexOf(country.description) > -1) {
              //  var index = this.lstCountry.indexOf(country.description);
              //  this.lstCountry.splice(index, 1);
              //}

              var index1 = this.lstCountry1.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index1 > -1) {
                this.lstCountry1.splice(index, 1);
              }

              //if (this.lstCountry1.indexOf(country.description) > -1) {
              //  var index = this.lstCountry1.indexOf(country.description);
              //  this.lstCountry1.splice(index, 1);
              //}

              var index2 = this.lstCountry2.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index2 > -1) {
                this.lstCountry2.splice(index, 1);
              }
            }
          });

          //remover os paises relativos a este continente
          this.countryList.forEach(country => {
            if (country.continent == "Oceania") {
              var index = this.contPais.indexOf(country);
              this.contPais.splice(index, 1);
            }
          });
        }
        break;
      case 'ASIA':
        if (this.inputAsia == false) {
          this.inputAsia = true;

          this.countryList.forEach(country => {
            if (country.continent == "Ásia") {
              if (count <= 19) {
                this.lstCountry.push(country)
              } else {
                if (count <= 39) {
                  this.lstCountry1.push(country);
                } else {
                  this.lstCountry2.push(country);
                }
              }
              this.contPais.push(country);
              count++;
            }
          });

          //this.lstCountry = ['Afeganistão', 'Arábia Saudita', 'Arménia', 'Azerbaijão', 'Bangladexe', 'Barém', 'Brunei', 'Butão', 'Camboja', 'Catar', 'Cazaquistão', 'China', 'Coreia do Norte', 'Coreia do Sul', 'Cuaite', 'Emirados Árabes Unidos', 'Estado da Palestina', 'Filipinas', 'Geórgia', 'Iémen'];
          //for (var i = 0; i <= this.lstCountry.length; i++) {
          //  this.contPais[this.lstCountry[i]] = true;
          //}
          //this.lstCountry1 = ['Iraque', 'Israel', 'Japão', 'Jordânia', 'Laus', 'Líbano', 'Malásia', 'Maldivas', 'Mianmar', 'Mongólia', 'Nepal', 'Omã', 'Paquistão', 'Quirguistão', 'Singapura', 'Síria', 'Sri Lanca', 'Tailândia', 'Taiuã', 'Tajiquistão'];
          //for (var i = 0; i <= this.lstCountry1.length; i++) {
          //  this.contPais[this.lstCountry1[i]] = true;
          //}
          //this.lstCountry2 = ['Turcomenistão', 'Turquia', 'Usbequistão', 'Vietname'];
          //for (var i = 0; i <= this.lstCountry2.length; i++) {
          //  this.contPais[this.lstCountry2[i]] = true;
          //}
          this.continenteName = continente;
        } else {
          this.inputAsia = false;
          //this.lstCountry = [];
          //this.lstCountry1 = [];
          //this.lstCountry2 = [];

          this.countryList.forEach(country => {
            if (country.continent == "Ásia") {
              var index = this.lstCountry.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index > -1) {
                this.lstCountry.splice(index, 1);
              }

              //if (this.lstCountry.indexOf(country.description) > -1) {
              //  var index = this.lstCountry.indexOf(country.description);
              //  this.lstCountry.splice(index, 1);
              //}

              var index1 = this.lstCountry1.findIndex(elem1 => {
                if (elem1.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index1 > -1) {
                this.lstCountry1.splice(index, 1);
              }

              //if (this.lstCountry1.indexOf(country.description) > -1) {
              //  var index = this.lstCountry1.indexOf(country.description);
              //  this.lstCountry1.splice(index, 1);
              //}

              var index2 = this.lstCountry2.findIndex(elem2 => {
                if (elem2.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index2 > -1) {
                this.lstCountry2.splice(index, 1);
              }
            }
          });

          //remover os paises relativos a este continente
          this.countryList.forEach(country => {
            if (country.continent == "Ásia") {
              var index = this.contPais.indexOf(country);
              this.contPais.splice(index, 1);
            }
          });
        }
        break;
      case 'AMERICA DO NORTE / SUL':
        if (this.inputAmericas == false) {
          this.inputAmericas = true;

          this.countryList.forEach(country => {
            if (country.continent == "América Norte" || country.continent == "América Central" || country.continent == "América Sul") {
              if (count <= 19) {
                this.lstCountry.push(country)
              } else {
                if (count <= 39) {
                  this.lstCountry1.push(country);
                } else {
                  this.lstCountry2.push(country);
                }
              }
              this.contPais.push(country);
              count++;
            }
          });
          //this.lstCountry = ['Antiga e Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belize', 'Bolívia', 'Brasil', 'Canadá', 'Chile', 'Colômbia', 'Costa Rica', 'Cuba', 'Dominica', 'Equador', 'Estados Unidos', 'Granada', 'Guatemala', 'Guiana'];
          //for (var i = 0; i <= this.lstCountry.length; i++) {
          //  this.contPais[this.lstCountry[i]] = true;
          //}

          //this.lstCountry1 = ['Haiti', 'Honduras', 'Jamaica', 'México', 'Nicarágua', 'Panamá', 'Paraguai', 'Peru', 'República Dominicana', 'Salvador', 'Santa Lúcia', 'São Cristóvão e Neves', 'São Vicente e Granadinas', 'Suriname', 'Trindade e Tobago', 'Uruguai', 'Venezuela'];
          //for (var i = 0; i <= this.lstCountry1.length; i++) {
          //  this.contPais[this.lstCountry1[i]] = true;
          //}

          //this.lstCountry2 = [];

          this.continenteName = continente;
        } else {
          this.inputAmericas = false;
          //this.lstCountry = [];
          //this.lstCountry1 = [];
          //this.lstCountry2 = [];

          this.countryList.forEach(country => {
            if (country.continent == "América Norte" || country.continent == "América Central" || country.continent == "América Sul") {
              var index = this.lstCountry.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index > -1) {
                this.lstCountry.splice(index, 1);
              }

              var index1 = this.lstCountry1.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index1 > -1) {
                this.lstCountry1.splice(index, 1);
              }

              var index2 = this.lstCountry2.findIndex(elem => {
                if (elem.description == country.description) {
                  return true;
                } else {
                  return false;
                }
              });
              if (index2 > -1) {
                this.lstCountry2.splice(index, 1);
              }
            }
          });

          //remover os paises relativos a este continente
          this.countryList.forEach(country => {
            if (country.continent == "América Norte" || country.continent == "América Central" || country.continent == "América Sul") {
              var index = this.contPais.indexOf(country);
              this.contPais.splice(index, 1);
            }
          });
        }
        break;

    }
  }

  valueInput() {
    this.inputTypeEuropa = this.inputEuropa;
    this.inputTypeOceania = this.inputOceania;
    this.inputTypeAmericas = this.inputAmericas;
    this.inputTypeAsia = this.inputAsia;
    this.inputTypeAfrica = this.inputAfrica;
  }

  inserirText(form: any) {
    console.log('Lista contPais', this.contPais);
    this.contPais.forEach(element => {
      var index = this.lstPaisPreenchido.findIndex(elem => {
        if (element.description == elem.description) {
          return true;
        }
        return false;
      });
      if (index == -1) {
        this.lstPaisPreenchido.push(element);
        console.log('Elementos na lista contPais ', element);
      }
    });
    
    
    console.log('Lista de todos os elementos passados (lstPaisPreenchido) ', this.lstPaisPreenchido);

    this.lstPaisPreenchido.forEach(country => {
      $('#text5').val($('#text5').val() + country.description + ', ' );
    });
  }

  redirectToClientById() {
    let navigationExtras: NavigationExtras = {
      state: {
        NIFNIPC: this.NIFNIPC,
        tipologia: this.tipologia
      }
    };
    this.route.navigate(["/clientbyid", this.router.snapshot.paramMap.get('id')], navigationExtras);
  }

  goBackToHomePage() {
    this.route.navigate(["/"]);
  }


}
